<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 3 Grundlagen R, R-Studio und Jamovi | A Minimal Book Example</title>
<meta name="author" content="Yihui Xie">
<meta name="description" content="3.1 Einführung In diesem Modul beschäftigen wir uns mit den Softwares, die wir für dieses Semester verwenden werden und wir wiederholen die Inhalte aus dem Seminar Statistik I. Folgende Submodule...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 3 Grundlagen R, R-Studio und Jamovi | A Minimal Book Example">
<meta property="og:type" content="book">
<meta property="og:description" content="3.1 Einführung In diesem Modul beschäftigen wir uns mit den Softwares, die wir für dieses Semester verwenden werden und wir wiederholen die Inhalte aus dem Seminar Statistik I. Folgende Submodule...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 3 Grundlagen R, R-Studio und Jamovi | A Minimal Book Example">
<meta name="twitter:description" content="3.1 Einführung In diesem Modul beschäftigen wir uns mit den Softwares, die wir für dieses Semester verwenden werden und wir wiederholen die Inhalte aus dem Seminar Statistik I. Folgende Submodule...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.9/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS -->
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">A Minimal Book Example</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled"><li><a class="" href="index.html"><span class="header-section-number">Chapter 3</span> Grundlagen R, R-Studio und Jamovi</a></li></ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="grundlagen-r-r-studio-und-jamovi" class="section level1" number="3">
<h1>
<span class="header-section-number">3</span> Grundlagen R, R-Studio und Jamovi<a class="anchor" aria-label="anchor" href="#grundlagen-r-r-studio-und-jamovi"><i class="fas fa-link"></i></a>
</h1>
<div id="einführung-1" class="section level2" number="3.1">
<h2>
<span class="header-section-number">3.1</span> Einführung<a class="anchor" aria-label="anchor" href="#einf%C3%BChrung-1"><i class="fas fa-link"></i></a>
</h2>
<p>In diesem Modul beschäftigen wir uns mit den Softwares, die wir für dieses Semester verwenden werden und wir wiederholen die Inhalte aus dem Seminar Statistik I. Folgende Submodule umfasst dieses Modul:</p>
<ul>
<li>Software des Seminars: In diesem Submodul erfährst du, welche Softwares wir für das Seminar verwenden und wie du diese installierst.</li>
<li>Grundlagen R: In diesem Submodul wiederholst du die grundlegenden Befehle in R und lernst, wie du mit R und R-Studio arbeiten kannst.</li>
<li>Grundlagen tidyverse: In diesem Submodul lernst du mit der Statistik-Software Jamovi umzugehen. Wir werden Jamovi in diesem Kurs verwenden, um statistische Fragestellungen zu beantworten.</li>
<li>Quiz Statistik I: An dieser Stelle wiederholst du zentrale Konzepte aus Statistik I, die Vorraussetzung für dieses Seminar sind.</li>
</ul>
</div>
<div id="software-des-seminars" class="section level2" number="3.2">
<h2>
<span class="header-section-number">3.2</span> Software des Seminars<a class="anchor" aria-label="anchor" href="#software-des-seminars"><i class="fas fa-link"></i></a>
</h2>
<p>Wir werden in diesem Kurs drei Softwares verwenden. R, R-Studio und Jamovi. R und R-Studio verwenden wir, um Daten zu bereinigen, deskriptive Daten zu berechnen und die Ergebnisse unserer Tests zu dokumentieren. Jamovi verwenden wir, um statistische Fragestellungen zu beantworten. Beide Softwares lassen sich miteinander integrieren, indem wir Ergebnisse aus Jamovi als Code in R übertragen können. Der Vorteil dieser Übertragung ist, dass du hierdurch keine Befehle in R lernen musst und dadurch ohne große Mühe statistische Testverfahren in R rechnen kannst. In diesem Modul lernst du diejenigen Kentnisse in R und Jamovi, die wir in diesem Seminar immer wieder brauchen.</p>
<ul>
<li>
<a href="https://www.r-project.org/">R</a>: R ist eine statistische Programmiersprache zur Analyse von Daten. Mit R werden wir in diesem Kurs Daten bereinigen und visualisieren. Datenvisualisierung ist ein zentraler Bestandteil der Datenanalyse, da wir durch Visualisierungen Muster in Daten erkennen können, die aus den Rohdaten schwer zu entnehmen sind. Zudem verwenden wir R für die Dokumentation unserer Ergebnisse. Die Dokumentation ist wichtig, da wir auch Jahre nach unserer Analyse verstehen möchten, wie wir die Daten ausgewertet haben. In SPSS oder Jamovi ist dies deutlich unübersichtlicher.</li>
<li>
<a href="https://rstudio.com/">R-Studio</a>: R-Studio ist eine Entwicklungsumgebung für die Programmiersprache R. Sie umfasst eine grafische Benutzeroberfläche und vereinfacht die Arbeit mit R.</li>
<li>
<a href="https://www.jamovi.org/">Jamovi</a>: Jamovi ist eine Software mit der man die gängigsten statistischen Verfahren in einer grafischen Benutzeroberfläche berechnen kann. In diesem Kurs verwenden wir Jamovi zur Berechnung der Verfahren und werden deren Ergebnisse in R übertragen. Zwar wird in der empirischen Sozialforschung häufig SPSS eingesetzt, allerdings ist SPSS kostenpflichtig und umfasst viele Verfahren, die wir in diesem Kurs nicht benötigen. Jamovi hat den Vorteil, dass es kostenlos ist und eine ähnliche Oberfläche wie SPSS hat. Der Transfer zu SPSS ist daher relativ einfach. Ein weiterer Grund für Jamovi ist, dass es sich sehr einfach mit R integrieren lässt.</li>
</ul>
</div>
<div id="download-der-software" class="section level2" number="3.3">
<h2>
<span class="header-section-number">3.3</span> Download der Software<a class="anchor" aria-label="anchor" href="#download-der-software"><i class="fas fa-link"></i></a>
</h2>
<p>Die drei Softwares sind unter folgenden Links kostenfrei für Mac und Windows zugänglich. Lade dir die Softwares gleich jetzt herunter. Wir werden alle drei Softwares in jedem Modul des Kurses verwenden.</p>
<ul>
<li>
<a href="https://ftp.gwdg.de/pub/misc/cran/">R &gt; 4.0.2</a>: Lade R in der Version 4.0.2 oder größer herunter.</li>
<li>
<a href="https://rstudio.com/products/rstudio/download/">R-Studio</a>: Lade die neueste Version von R-Studio herunter.</li>
<li>
<a href="https://www.jamovi.org/download.html">Jamovi 1.2 solid</a>: Lade die Version 1.1.9 solid von Jamovi herunter.</li>
</ul>
</div>
<div id="warum-so-viele-softwares" class="section level2" number="3.4">
<h2>
<span class="header-section-number">3.4</span> Warum so viele Softwares?<a class="anchor" aria-label="anchor" href="#warum-so-viele-softwares"><i class="fas fa-link"></i></a>
</h2>
<p>Es ist heutzutage nicht mehr möglich Statistik ohne Software zu betreiben. Wir werden in diesem Kurs versuchen, diejenigen Softwares zu verwenden, mit denen du am einfachsten Daten analysieren und statistische Verfahren berechnen kannst. Ein paar Fragen könntest du dir an dieser Stelle dennoch stellen:</p>
<ul>
<li>
<strong>Warum überhaupt R?</strong> Keine Datenanalyse kommt ohne die Verarbeitung von Daten aus. Stell dir beispielsweise vor du möchtest neue Variablen berechnen bzw. ein Balkendiagramm erstellen. Solche Datenveränderungen und Visualisierungen lassen sich in R sehr elegant mit dem Paket<a href="https://www.tidyverse.org/">tidyverse</a>umsetzen. Zudem ermöglicht uns das Paket<a href="https://ggplot2.tidyverse.org/">ggplot2</a> die Visualisierung von Daten. R ist zudem kostenfrei und kann sowohl auf Mac als auch auf Windows installiert werden.</li>
<li>
<strong>Warum nicht alles in R?</strong> R hat für Beginner eine steile Lernkurve. Viele statistische Verfahren lassen sich direkt in R berechnen (z.B.<a href="https://cran.r-project.org/web/packages/psych/index.html">psych</a>,<a href="https://cran.r-project.org/web/packages/car/index.html">car</a>), jedoch muss man hierfür häufig mehrere Pakete installieren und diese ebenso anwenden können. Wir vermeiden dies in diesem Kurs, indem wir die Analysen in Jamovi umsetzen.</li>
<li>
<strong>Warum nicht alles in SPSS?</strong> SPSS ist eine in der Sozialforschung beliebte Software, um statistische Verfahren zu rechnen. SPSS ist allerdings kostenpflichtig. Da es kostenfreie Alternativen gibt, die alle Verfahren dieses Kurses abdecken, rechnen wir mit Jamovi. Wenn man Jamovi verstanden hat, ist der Transfer zu SPSS einfach.</li>
</ul>
</div>
<div id="grundlagen-r" class="section level2" number="3.5">
<h2>
<span class="header-section-number">3.5</span> Grundlagen R<a class="anchor" aria-label="anchor" href="#grundlagen-r"><i class="fas fa-link"></i></a>
</h2>
<p>In diesem Submodul lernst du zentrale Befehle in R, welche du immer wieder verwenden wirst. Genauer gehen wir auf folgende Themen ein:</p>
<ul>
<li>Umgang mit R-Studio</li>
<li>Pakete installieren und laden</li>
<li>Das Arbeitsverzeichnis</li>
<li>Datensätze importieren</li>
<li>Grundlegende Operatoren</li>
<li>Grundlegende Funktionen in R</li>
<li>Daten exportieren</li>
</ul>
<div id="umgang-mit-r-studio" class="section level3" number="3.5.1">
<h3>
<span class="header-section-number">3.5.1</span> Umgang mit R-Studio<a class="anchor" aria-label="anchor" href="#umgang-mit-r-studio"><i class="fas fa-link"></i></a>
</h3>
<p>R-Studio ist eine Entwicklungsumgebung für die Programmiersprache R. R-Studio vereinfacht dir die Arbeit mit R, indem es beispielsweise einen Editor integriert, in welchen du R-Code schreiben kannst. R-Studio hat vier zentrale Fenster:</p>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-2"></span>
<img src="images/02_grundlagen/rstudio_panels.jpg" alt="Die vier zentralen Fenster von R-Studio" width="640"><p class="caption">
Figure 3.1: Die vier zentralen Fenster von R-Studio
</p>
</div>
<ul>
<li>Im Skript links oben findest du die R-Skripte. Dort speicherst du diejenigen Befehle, welche du auf jeden Fall speichern möchtest. Beispielsweise ein statistisches Verfahren, mit welchem du eine Hypothesen prüfst oder eine Visualisierung, die du erstellt hast.</li>
<li>In der Konsole links unten probierst du verschiedene Befehle aus. Die Konsole ist flüchtig und daher kein Ort, um dauerhaft Berechnungen zu sichern. Hierfür verwendest du am besten das Skript.</li>
<li>Das Environment und die History im Fenster rechts oben ist für diesen Kurs weniger relevant. Im Environment siehst du, auf welche Variablen und Daten du zugreifen kannst.</li>
<li>Rechts unten findest du den Output und die Plots/Visualisierungen. In der Regel schaust du hier deine Visualisierungen an, die du im Skript bzw. in der Konsole erstellst.</li>
</ul>
</div>
<div id="befehle-aus-der-konsole-ausführen" class="section level3" number="3.5.2">
<h3>
<span class="header-section-number">3.5.2</span> Befehle aus der Konsole ausführen<a class="anchor" aria-label="anchor" href="#befehle-aus-der-konsole-ausf%C3%BChren"><i class="fas fa-link"></i></a>
</h3>
<p>Befehle lassen sich sowohl in der Konsole als auch im Skript ausführen. Als Faustregel: Die Konsole dient dem Herumspielen mit den Daten, im Skript schreibst du alle Befehle auf, die du gerne behalten möchtest. Nehmen wir an, du möchtest die Zahl 5 mit der Zahl 8 addieren:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">5</span> <span class="op">+</span> <span class="fl">8</span></code></pre></div>
<pre><code>## [1] 13</code></pre>
<p>Um den Befehl in der Konsole auszuführen, drückst du die <strong>ENTER-Taste</strong></p>
<p>Anschließend erhältst du das Ergebnis der Berechnung. Um diesen Output aus der Konsole wieder zu entfernen, kannst du die Tastenkombination <strong>STRG+L</strong> verwenden. Hierdurch verschwindet der Output:</p>
<div class="inline-figure"><img src="images/02_grundlagen/console.png" width="410"></div>
<p>Wenn du eine Grafik erstellst (den Code musst du an dieser Stelle nicht verstehen), wird der Output in dem Plots Panel angezeigt, ohne dass du in der Konsole einen Output erhältst:</p>
<div class="inline-figure"><img src="images/02_grundlagen/plot.png" width="840"></div>
</div>
<div id="befehle-aus-dem-skript-ausführen" class="section level3" number="3.5.3">
<h3>
<span class="header-section-number">3.5.3</span> Befehle aus dem Skript ausführen<a class="anchor" aria-label="anchor" href="#befehle-aus-dem-skript-ausf%C3%BChren"><i class="fas fa-link"></i></a>
</h3>
<p>Genau die gleichen Befehle kannst du aus einem Skript ausführen (Um ein neues Skript zu öffnen drücke <strong>STRG + UMSCHALT + N</strong> auf deiner Tastatur):</p>
<div class="inline-figure"><img src="images/02_grundlagen/befehle_skrip.jpg" width="410"></div>
<p>Um diesen Befehl auszuführen, musst du Deinen Cursor auf die jeweilige Zeile legen und <strong>STRG+ENTER</strong> drücken (für Mac-Nutzer: command + enter):</p>
<div class="inline-figure"><img src="images/02_grundlagen/befehle_skript1.png" width="414"></div>
<p>Wenn du ENTER-Taste nicht drückst, springt der Cursor in die nächste Zeile, ohne dass der Befehl ausgeführt wird. Alternativ kannst du die Zeile ausführen, indem du den Button Run drückst:</p>
<div class="inline-figure"><img src="images/02_grundlagen/run.png" width="414"></div>
<p>Um mehrere Zeilen ausführen, musst du mehrere Zeilen selektieren und STRG+ENTER drücken:</p>
<div class="inline-figure"><img src="images/02_grundlagen/multi_run.jpg" width="412"></div>
</div>
<div id="pakete-installieren-und-laden" class="section level3" number="3.5.4">
<h3>
<span class="header-section-number">3.5.4</span> Pakete installieren und laden<a class="anchor" aria-label="anchor" href="#pakete-installieren-und-laden"><i class="fas fa-link"></i></a>
</h3>
<p>Ein Paket ist eine Sammlung an Funktionen und Daten, welche du gebündelt herunterladen kannst. Pakete erweitern die Funktionalität von R. R hat bereits viele Funktionen, die wir für die Datenanalyse verwenden können. Beispielsweise umfasst R die Funktion mean, mit der wir Mittelwerte aus einer Variablen berechnen können. Selbst wenn R hunderte Funktionen hat, die mit R mitgeliefert werden, brauchen wir häufig weitere Funktionen, um unsere Daten zu analysieren. Für diesen Kurs benötigen wir insbesondere Pakete, mit denen wir Daten analysieren, visualisieren und auswerten können. In diesem Kurs verwenden wir folgende Pakete:</p>
<ul>
<li>
<a href="https://rise.articulate.com/author/SHojwTyVccfVjJhG_D37L6cXrgxGbnca#/author/details/anYDnxw9kjDldfma4gUcOvsHCpVUSe5-">tidyverse</a>: Tidyverse umfasst eine Vielzahl an Paketen zur Analyse und Verarbeitung von Daten. Die Pakete haben eine einheitliche Philosophie und arbeiten reibungslos miteinander.</li>
<li>
<a href="https://cran.r-project.org/web/packages/jmv/index.html">jmv &gt;= 1.2.23</a>: jmv ist ein Paket, welches mit Jamovi zusammen arbeitet und uns ermöglicht, die Analysen, die wir in Jamovi umgesetzt haben, in R zu übertragen.</li>
<li>
<a href="https://github.com/sfirke/janitor">janitor</a>: Viele Datensätze sind unstrukturiert und enthalten komplexe Variablennamen. Mit dem Paket janitor können wir diese bereinigen.</li>
<li>
<a href="https://github.com/r-lib/styler">styler</a>: Mit styler können wir unseren Code so formatieren, dass er den Gestaltungsrichtlinien entspricht. Beispielsweise möchten wir nicht, dass eine Zeile Code länger als 80 Zeilen ist. Mit Hilfe von styler können wir solche Fehler durch einen Klick korrigieren.</li>
</ul>
<p>Du kannst zu jeder Zeit in R-Studio sehen, welche Pakete installiert sind, indem du dir den Package Panel anschaust (rechts unten in R-Studio):</p>
<div class="inline-figure"><img src="images/02_grundlagen/pakete.png" width="541"></div>
<div id="pakete-intallieren" class="section level4" number="3.5.4.1">
<h4>
<span class="header-section-number">3.5.4.1</span> Pakete intallieren<a class="anchor" aria-label="anchor" href="#pakete-intallieren"><i class="fas fa-link"></i></a>
</h4>
<p>Um Pakete zu installieren, kannst du in R-Studio auf Install unter dem Fenster Packages klicken:</p>
<div class="inline-figure"><img src="images/02_grundlagen/install_pakete.png" width="577"></div>
<p>Trage zunächst das Paket unter Packages ein und drücke anschließend auf Install. Installiere sowohl tidyverse, janitor, jmv als auch styler. Alternativ kannst du direkt den Befehl in die Konsole eingeben, um die Pakete zu installieren (führe die Befehle am besten nacheinander aus):</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"tidyverse"</span><span class="op">)</span>
<span class="co"># Dann</span>
<span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"janitor"</span><span class="op">)</span>
<span class="co"># Dann</span>
<span class="fu">install.packags</span><span class="op">(</span><span class="st">"jmv"</span><span class="op">)</span>
<span class="co"># Dann</span>
<span class="fu">install.packags</span><span class="op">(</span><span class="st">"styler"</span><span class="op">)</span></code></pre></div>
<p>Prüfe anschließend, ob alle Pakete installiert wurden. Suche hierfür die Pakete in dem Panel Packages:</p>
<div class="inline-figure"><img src="images/02_grundlagen/pakete_check.png" width="549"></div>
</div>
<div id="pakete-laden" class="section level4" number="3.5.4.2">
<h4>
<span class="header-section-number">3.5.4.2</span> Pakete laden<a class="anchor" aria-label="anchor" href="#pakete-laden"><i class="fas fa-link"></i></a>
</h4>
<p>Um die Funktionalität eines Paketes verwenden zu können, ist es mit der Installation nicht getan. Wir müssen die Pakete zusätzlich laden. Am besten lädst du die Pakete immer am Anfang deines R-Skripts, indem du folgende Befehl für jedes Paket eingibst:</p>
<pre><code>&gt;     library(tidyverse)
&gt;     library(jmv)</code></pre>
<p>Um anschließend zu prüfen, welche Pakete gerade geladen sind, kannst du den Befehl sessionInfo() ausführen:</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## R version 4.1.0 (2021-05-18)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 22000)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
## [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
## [5] LC_TIME=German_Germany.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] forcats_0.5.1   stringr_1.4.0   dplyr_1.0.6     purrr_0.3.4    
## [5] readr_1.4.0     tidyr_1.1.3     tibble_3.1.2    ggplot2_3.3.4  
## [9] tidyverse_1.3.1
## 
## loaded via a namespace (and not attached):
##  [1] tidyselect_1.1.1 xfun_0.24        bslib_0.3.1      haven_2.4.1     
##  [5] colorspace_2.0-1 vctrs_0.3.8      generics_0.1.0   htmltools_0.5.2 
##  [9] yaml_2.2.1       utf8_1.2.1       rlang_0.4.11     jquerylib_0.1.4 
## [13] pillar_1.6.1     withr_2.4.2      glue_1.4.2       DBI_1.1.1       
## [17] dbplyr_2.1.1     readxl_1.3.1     modelr_0.1.8     jpeg_0.1-8.1    
## [21] lifecycle_1.0.0  cellranger_1.1.0 munsell_0.5.0    gtable_0.3.0    
## [25] rvest_1.0.0      memoise_2.0.0    evaluate_0.14    knitr_1.33      
## [29] fastmap_1.1.0    fansi_0.5.0      highr_0.9        broom_0.7.7     
## [33] Rcpp_1.0.7       backports_1.2.1  scales_1.1.1     cachem_1.0.5    
## [37] jsonlite_1.7.2   fs_1.5.0         png_0.1-7        hms_1.1.0       
## [41] digest_0.6.27    stringi_1.6.2    bookdown_0.24    grid_4.1.0      
## [45] cli_3.0.1        tools_4.1.0      magrittr_2.0.1   sass_0.4.0      
## [49] crayon_1.4.1     pkgconfig_2.0.3  downlit_0.4.0    ellipsis_0.3.2  
## [53] xml2_1.3.2       reprex_2.0.0     lubridate_1.7.10 assertthat_0.2.1
## [57] rmarkdown_2.9    httr_1.4.2       rstudioapi_0.13  R6_2.5.0        
## [61] compiler_4.1.0</code></pre>
<p>Unter loaded via namespace kannst du erkennen, welche Pakete installiert sind, aber nicht geladen sind. Unter other attached packages siehst du, welche Pakete geladen sind, beispielsweise jmv. Erst nachdem ein Paket geladen ist, kannst du die Funktionen der Pakete verwenden. Wenn du R-Studio neu startest, muss jedes Paket immer neu geladen werden. Diesen Schritt vergisst man häufig, wodurch Fehler entstehen. Stelle daher immer sicher, dass du die nötigen Pakete lädst, bevor du Funktionen der Pakete verwendest. Um zu prüfen, aus welchem Paket eine Funktion stammt, setze ein Fragezeichen vor die Funktion (siehe nächstes Bild links oben). Anschließend siehst du die Dokumentation dieses Befehls in dem Panel Help:</p>
<div class="inline-figure"><img src="images/02_grundlagen/panel_help.jpg" width="840"></div>
</div>
</div>
<div id="das-arbeitsverzeichnis" class="section level3" number="3.5.5">
<h3>
<span class="header-section-number">3.5.5</span> Das Arbeitsverzeichnis<a class="anchor" aria-label="anchor" href="#das-arbeitsverzeichnis"><i class="fas fa-link"></i></a>
</h3>
<p>Wenn du R öffnest, legt R im Hintergrund immer einen Ordner fest, aus dem du alle Dateien importierst und exportierst. Diesen Ordner nennt man das Arbeitsverzeichnis. Du kannst dir das Arbeitsverzeichnis in R anzeigen lassen, indem du folgenden Befehl in der Konsole ausführst:</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/getwd.html">getwd</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "C:/Users/Christian Burkhart/repositories/statistik_ii_bookdown"</code></pre>
<p>Als Output erhältst du das Verzeichnis des Ordners, welcher gerade als Arbeitsverzeichnis bestimmt ist.</p>
<p>Solange du in R nicht mit <a href="https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects">Projekten</a> arbeitest, musst du wissen, wo das Arbeitsverzeichnis liegt, um Dateien zu importieren. Wenn du beispielsweise folgenden Befehl verwendest, um die Datei human_resources.csv einzulesen, nimmt R automatisch an, dass sich diese Datei im Arbeitsverzeichnis befindet:</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Nehmen wir an, dass sich das Arbeitsverzeichnis </span>
<span class="co"># in folgendem Ordner befindet: </span>
<span class="co">#    C:/Users/Christian/Dropbox/Lehre</span>
<span class="va">human_resources</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"human_resources.csv"</span><span class="op">)</span></code></pre></div>
<p>Der Text zwischen den Anführungszeichen wird auch als relativer Pfad bezeichnet. Liegt die Datei beispielsweise einen Ordner über dem Arbeitsverzeichnis (in unserem Beispiel im Ordner Dropbox), verwenden wir zwei Punkte, um einen Ordner nach oben zu klettern:</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Nehmen wir an, dass sich das Arbeitsverzeichnis </span>
<span class="co"># in folgendem Ordner befindet: </span>
<span class="co">#    C:/Users/Christian/Dropbox/Lehre</span>
<span class="va">human_resources</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"../human_resources.csv"</span><span class="op">)</span></code></pre></div>
<p>Nun sucht R die Datei <em>human_resources.csv</em> im Ordner Dropbox. Die einfachste Methode, um allerdings eine Datei zu importieren, ist, das Arbeitsverzeichnis dort festzulegen, wo die Datei gespeichert ist. Dies können wir tun, indem wir den Shortcut <strong>Ctrl+ UMSCHALT + H</strong> in R-Studio ausführen. Danach öffnet sich ein Fenster, in dem wir das Arbeitsverzeichnis bestimmen können.</p>
</div>
<div id="datensätze-importieren" class="section level3" number="3.5.6">
<h3>
<span class="header-section-number">3.5.6</span> Datensätze importieren<a class="anchor" aria-label="anchor" href="#datens%C3%A4tze-importieren"><i class="fas fa-link"></i></a>
</h3>
<p>In diesem Kurs arbeiten wir mit Daten, die in Tabellen angeordnet sind. Häufig liegen Daten als Excel-Dateien vor. Ein gängiges Format, um Daten zu speichern sind allerdings <a href="https://de.wikipedia.org/wiki/CSV_(Dateiformat)">CSV-Dateien</a>. CSV steht für Comma Seperated Values. Dies bedeutet, dass Werte in CSV-Dateien entweder durch ein Komma oder ein Semikolon getrennt sind. In folgendem Beispiel siehst du ein Datensatz mit drei Variablen, die in jeder Reihe durch ein Komma getrennt sind:</p>
<pre><code>id,variable1,variable2
ku22su99,2,3
nn08se21,5,6</code></pre>
<p>Da CSV-Dateien ein sehr bekanntes Dateiformat für Daten sind, lassen sich CSV-Dateien sowohl in Excel, Jamovi, SPSS, als auch R importieren (<a href="https://support.microsoft.com/de-de/office/importieren-oder-exportieren-von-textdateien-txt-oder-csv-5250ac4c-663c-47ce-937b-339e391393ba?ui=de-de&amp;rs=de-de&amp;ad=de">Excel</a>, <a href="https://www.youtube.com/watch?v=-imCiECplPo">SPSS</a>, <a href="https://www.youtube.com/watch?v=R0uE4LlHeac">Jamovi</a>). Wir werden in diesem Modul mit dem Datensatz <a href="data/human_resources.csv">human_resources.csv</a> arbeiten.</p>
<p>Eine CSV-Datei können wir in R importieren, indem wir die Datei in dem <em>Panel Files</em> suchen und auf die Datei klicken. Klicke anschließend auf auf <em>Import Dataset</em>:</p>
<div class="inline-figure"><img src="images/02_grundlagen/csv_.png" width="496"></div>
<p>Anschließend siehst du ein neues Fenster, in welchem der Code angezeigt wird, mit dem wir die Daten importieren können. Kopiere am einfachsten die zweite Zeile des Code Preview (gelb markiert) und drücke dann auf Cancel.</p>
<p>Falls die Daten nicht sauber in Spalten angeordnet sind, kannst du unter dem Reiter <em>Delimiter</em> die Trennzeichen ändern. Im folgenden Beispiel sind die Trennzeichen in der CSV-Datei Kommas.</p>
<div class="inline-figure"><img src="images/02_grundlagen/table.jpg" width="840"></div>
<p>Diesen kopierten Code fügst du in dein R-Skript ein. Achte darauf, dass du vorher das Paket tidyverse lädst:</p>
<div class="figure">
<span style="display:block;" id="fig:unnamed-chunk-21"></span>
<img src="images/02_grundlagen/load_dataset.jpg" alt="Beispiel für das Laden eines Datensatzes mit dem Paket tidyverse" width="323"><p class="caption">
Figure 3.2: Beispiel für das Laden eines Datensatzes mit dem Paket tidyverse
</p>
</div>
<p>Im nächsten Schritt liest du den Datensatz ein, indem du den Befehl ausführst:</p>
<div class="inline-figure"><img src="images/02_grundlagen/load_data1.png" width="456"></div>
<p>Die rote Schrift hat keine Bedeutung. Sie zeigt an, welche Variablen der Datensatz umfasst. Um zu prüfen, ob der Datensatz in der Variable gespeichert wurde, gib den Datensatz in der Konsole aus:</p>
<div class="inline-figure"><img src="images/02_grundlagen/enviroment.png" width="456"></div>
<p>Gleichzeitig kannst du im Panel Environment sehen, ob dein Datensatz geladen wurde:</p>
<div class="inline-figure"><img src="images/02_grundlagen/environment1.png" width="502"></div>
<p>Der Output zeigt uns an, dass der Datensatz 1470 Reihen und 17 Variablen hat.</p>
</div>
<div id="grundlegende-operatoren-in-r" class="section level3" number="3.5.7">
<h3>
<span class="header-section-number">3.5.7</span> Grundlegende Operatoren in R<a class="anchor" aria-label="anchor" href="#grundlegende-operatoren-in-r"><i class="fas fa-link"></i></a>
</h3>
<div id="rechenoperationen" class="section level4" number="3.5.7.1">
<h4>
<span class="header-section-number">3.5.7.1</span> Rechenoperationen<a class="anchor" aria-label="anchor" href="#rechenoperationen"><i class="fas fa-link"></i></a>
</h4>
<p>R umfasst die typischen Rechenoperatoren, die du aus der Schule kennst. Du kannst mit R Plus, Minus oder Geteilt rechnen.</p>
<p>Zahlen voneinander teilen:</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">3</span> <span class="op">/</span> <span class="fl">9</span></code></pre></div>
<pre><code>## [1] 0.3333333</code></pre>
<p>Das Produkt zweier Zahlen berechnen:</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">3</span> <span class="op">*</span> <span class="fl">4</span></code></pre></div>
<pre><code>## [1] 12</code></pre>
<p>Zwei Zahlen miteinander addieren:</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">3</span> <span class="op">+</span> <span class="fl">4</span> </code></pre></div>
<pre><code>## [1] 7</code></pre>
<p>Die Zeichen +, -, / oder * nennen wir Operatoren. Operatoren sind nichts anderes als besondere Symbole, die eine bestimmte Aufgabe haben. Zum Beispiel hat der Operator + die Aufgabe, zwei Zahlen zu addieren. Wir können ebenso mehrere Operatoren miteinander verschachteln:</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="op">(</span><span class="fl">3</span> <span class="op">/</span> <span class="fl">9</span><span class="op">)</span> <span class="op">*</span> <span class="fl">4</span> <span class="op">+</span> <span class="fl">3</span></code></pre></div>
<pre><code>## [1] 4.333333</code></pre>
</div>
<div id="der-zuordnungsoperator" class="section level4" number="3.5.7.2">
<h4>
<span class="header-section-number">3.5.7.2</span> Der Zuordnungsoperator<a class="anchor" aria-label="anchor" href="#der-zuordnungsoperator"><i class="fas fa-link"></i></a>
</h4>
<p>Der Zuordnungsoperator &lt;- wird verwendet, um Variablen zu kreiieren. Variablen kannst du dir wie Boxen bei einem Umzug vorstellen, die etwas enthalten. Jede Box bekommt ein Label, hier einen Variablennamen. Was in der Box steckt, kannst du erfahren, indem du die Box aufmachst, bzw. dir die Variable in R ausgeben lässt. Erstellen wir hierzu eine neue Variable mit dem Namen sum_score:</p>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sum_score</span> <span class="op">&lt;-</span> <span class="fl">3</span> <span class="op">+</span> <span class="fl">4</span></code></pre></div>
<p>Jede Variable umfasst drei Elemente:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Der Variablenname</strong>: sum_score beispielsweise. Dieser Name ist willkürlich. Er sollte nicht mit einer Zahl beginnen und kleingeschrieben sein. Trenne mehrere Wörter am besten mit einem Unterstrich (z.B. sum_score).</p></li>
<li><p><strong>Der Zuordnungsoperator &lt;-:</strong> Achte darauf, dass vor dem &lt; und hinter dem - ein Leerzeichen steht. Ebenso sollte zwischen Operatoren ein Leerzeichen stehen. Falsch: sum_score&lt;-3+4, falsch: sum_score &lt;- 3+4, richtig: sum_score &lt;- 3 + 4.</p></li>
<li><p><strong>Der Inhalt der Variable:</strong> 3 + 4. Der Inhalt kann im Prinzip alles sein: Text: “Hallo,” ein Datensatz: read_csv(…) oder der Output einer Funktion: mean(c(1, 3, 4))</p></li>
</ol>
<p>Wenn du eine Variable erstellst, passiert zunächst nichts. R speichert intern das Produkt in der Variable sum_score. Um das Ergebnis der Berechnung zu sehen, führe die Variable in R aus:</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sum_score</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<p>Variablennamen sollten immer so geschrieben sein, dass man weiß, was in der Variable steckt:</p>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">x</span> <span class="op">&lt;-</span> <span class="fl">3</span> <span class="op">+</span> <span class="fl">2</span> <span class="co"># schlecht</span>
<span class="va">summe_zahlen</span> <span class="op">&lt;-</span> <span class="fl">3</span> <span class="op">+</span> <span class="fl">2</span> <span class="co"># besser</span></code></pre></div>
<p>Trenne einzelne Wörter in der Variable mit einem Unterstrich:</p>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">my_age</span> <span class="op">&lt;-</span> <span class="fl">24</span>  <span class="co"># gut</span>

<span class="va">my.age</span> <span class="op">&lt;-</span> <span class="fl">24</span> <span class="co"># schlecht</span>
<span class="va">my</span><span class="op">-</span><span class="va">age</span> <span class="op">&lt;-</span> <span class="fl">24</span> <span class="co"># schlecht</span>
<span class="va">my</span><span class="op">/</span><span class="va">age</span> <span class="op">&lt;-</span> <span class="fl">24</span> <span class="co"># schlecht</span></code></pre></div>
<p>Schreibe Variablen am besten alle Buchstaben des Variablennamen in Kleinschreibung:</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">my_age</span> <span class="op">&lt;-</span> <span class="fl">24</span>

<span class="co"># nicht:</span>
<span class="va">My_age</span> <span class="op">&lt;-</span> <span class="fl">24</span></code></pre></div>
<p>Variablen sollten exakt angegeben werden. Kleinste Fehler führen zu Fehlern. Zum Beispiel macht die Groß- oder Kleinschreibung einen Unterschied:</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">my_age</span> <span class="op">&lt;-</span> <span class="fl">24</span>
<span class="va">My_age</span>
<span class="co"># Error: object 'My_age' not found</span></code></pre></div>
</div>
<div id="der-operator" class="section level4" number="3.5.7.3">
<h4>
<span class="header-section-number">3.5.7.3</span> Der == Operator<a class="anchor" aria-label="anchor" href="#der-operator"><i class="fas fa-link"></i></a>
</h4>
<p>Wir können ebenso prüfen, ob zwei Werte gleich sind, indem wir den == Operator verwenden:</p>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">3</span> <span class="op">==</span> <span class="fl">4</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>Oder:</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">3</span> <span class="op">==</span> <span class="fl">3</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Oder:</p>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">3</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">+</span> <span class="fl">2</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>Später werden wir diesen Operator verwenden, um Reihen in einem Datensatz zu filtern. Eine volle Liste der restlichen Operatoren findest du <a href="https://www.statmethods.net/management/operators.html">hier</a>.</p>
</div>
</div>
<div id="funktionen" class="section level3" number="3.5.8">
<h3>
<span class="header-section-number">3.5.8</span> Funktionen<a class="anchor" aria-label="anchor" href="#funktionen"><i class="fas fa-link"></i></a>
</h3>
<p>Jede Programmiersprache ist nur so umfangreich, wie viele Funktionen sie hat. Funktionen werden von Menschen geschrieben, deren Ziel es ist, verschiedenste Berechnungen zu automatisieren. Gib zum Beispiel einmal in deine Konsole nur die Funktion mean ein. Was du erhältst ist der Beginn einer Funktion, die Menschen für die Programmiersprache R geschrieben haben. Funktionen haben immer den gleichen Aufbau:</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">function_name</span><span class="op">(</span>argument1 <span class="op">=</span> <span class="va">value1</span>, argument2 <span class="op">=</span> <span class="va">value2</span><span class="op">)</span></code></pre></div>
<ul>
<li>
<strong>function_name</strong>: Dies ist der Name der Funktion. Auch dieser ist wie bei Variablen willkürlich gewählt.</li>
<li>
<strong>argument1</strong>: Funktionen haben immer Argumente. Ein Argument besagt, welche Objekte in eine Funktion gespeist werden. Stell dir Funktionen wie eine Fabrik vor, die etwas herstellt. Jede Fabrik benötigt Rohmaterial mit dem Produkte erzeugt werden. Argumente sind äquivalent zu Rohmaterialien. Sie werden in die Funktion gespeist und in der Funktion verarbeitet.</li>
<li>
<strong>value1</strong>: Jedes dieser Rohmaterialien hat bestimmte Werte. Beispielsweise kann value1 eine Zahl (3) oder ein Text sein (“Hallo”). Wir werden später andere Datentypen kennen lernen, die ebenso in Funktionen gespeist werden können (z.B. Vektoren oder Dataframes - mehr dazu gleich).</li>
</ul>
<p>Beispielsweise umfasst R die Funktion sqrt mit der wir die Wurzel einer Zahl berechnen können:</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fl">9</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>Mit Hilfe des ? Zeichens können wir die Funktion näher betrachten und uns ansehen, welche Argumente eine Funktion annimmt:</p>
<div class="inline-figure"><img src="images/02_grundlagen/funktion.png" width="550"></div>
<p>Die Funktion sqrt hat demnach nur ein Argument mit dem Namen x. x kann sowohl eine einzelne Zahl als auch mehrere Zahlen sein. Wir müssen das Argument nicht immer angeben. Wir hätten die Funktion daher auch so formulieren können:</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fl">9</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>Achte darauf, dass jede Funktion mit einer Klammer schließt. Tust du dies nicht, denkt R, dass dein Befehl noch nicht zu Ende ist und zeigt Dir dies mit einem + an:</p>
<pre><code>sqrt(9
+</code></pre>
<p>Eine andere Funktion heißt sum. Mit sum kannst du mehrere Zahlen miteinander addieren:</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 12</code></pre>
<p>Wenn du dir die Funktion unter der Hilfe mit ?sum anschaust, erkennst du, dass die Funktion unendlich viele Argumente hat. Dies wird mit einem … gekennzeichnet:</p>
<div class="inline-figure"><img src="images/02_grundlagen/sum.png" width="333"></div>
<p>Wir könnten daher ebenso die Summe von fünf Zahlen zusammen rechnen:</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span>, <span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 15</code></pre>
<p>Lade als nächstes das Paket tidyverse (library(tidyverse)). Das Paket tidyverse umfasst die Funktion select. Mit Hilfe von select werden wir später Variablen aus einem Datensatz selektieren. Wenn du dir die Dokumentation der Funktion mit Hilfe von ?select anschaust, erkennst du, dass die Funktion mehrere Argumente hat:</p>
<div class="inline-figure"><img src="images/02_grundlagen/select.png" width="536"></div>
<p>Das erste Argument heißt .data. Hierfür fügen wir später den Datensatz ein. Das zweite Argument hat keinen expliziten Namen, sondern umfasst eine mit Komma getrennte Liste an Variablennamen. Schauen wir uns ein Beispiel an. Hierfür laden wir zunächst das Paket tidyverse und den Datensatz <em>human_resources</em>:</p>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="va">human_resources</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"human_resources.csv"</span><span class="op">)</span></code></pre></div>
<p>Anschließend können wir die Funktion select ausführen, um verschiede Variablen aus dem Datensatz zu nehmen (Um zu sehen, welche Variablen im Datensatz stecken, gebe colnames(human_resources) in die Konsole ein):</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span>.data <span class="op">=</span> <span class="va">human_resources</span>, <span class="va">id</span>, <span class="va">age</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 2
##       id   age
##    &lt;dbl&gt; &lt;dbl&gt;
##  1     1    41
##  2     2    49
##  3     3    37
##  4     4    33
##  5     5    27
##  6     6    32
##  7     7    59
##  8     8    30
##  9     9    38
## 10    10    36
## # ... with 1,460 more rows</code></pre>
<p>Du erkennst das erste Argument .data, in welches wir den Datensatz einfügen. Zusätzlich geben wir mehrere Variablennamen ein, indem wir die Variablennamen durch ein Komma trennen. Wir hätten ebenso die Argumente umdrehen können:</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">age</span>, .data <span class="op">=</span> <span class="va">human_resources</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 2
##       id   age
##    &lt;dbl&gt; &lt;dbl&gt;
##  1     1    41
##  2     2    49
##  3     3    37
##  4     4    33
##  5     5    27
##  6     6    32
##  7     7    59
##  8     8    30
##  9     9    38
## 10    10    36
## # ... with 1,460 more rows</code></pre>
<p>Generell ist es allerdings ratsam, die Reihenfolge der Argumente beizubehalten. Wenn wir dies tun, können wir die Namen der Argumente ignorieren:</p>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">human_resources</span>, <span class="va">id</span>, <span class="va">age</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 2
##       id   age
##    &lt;dbl&gt; &lt;dbl&gt;
##  1     1    41
##  2     2    49
##  3     3    37
##  4     4    33
##  5     5    27
##  6     6    32
##  7     7    59
##  8     8    30
##  9     9    38
## 10    10    36
## # ... with 1,460 more rows</code></pre>
<p>Versuchen wir nochmal von diesem Beispiel zu abstrahieren. Funktionen haben einen Namen und eine umgebende Klammer:</p>
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">function_name</span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p>Fasst alle Funktionen haben Argumente. Die Anzahl der Argumente ist abhängig von der Funktion. Hier siehst du das Schema einer Funktion mit zwei Argumenten:</p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">function_name</span><span class="op">(</span>argument1 <span class="op">=</span> <span class="va">value1</span>, argument2 <span class="op">=</span> <span class="va">value2</span><span class="op">)</span></code></pre></div>
<p>Die Reihenfolge der Argumente ist egal, solange wir die Argumente explizit benennen:</p>
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">function_name</span><span class="op">(</span>argument2 <span class="op">=</span> <span class="va">value2</span>, argument1 <span class="op">=</span> <span class="va">value1</span><span class="op">)</span></code></pre></div>
<p>Bennenen wir die Argumente nicht, müssen wir die Reihenfolge beachten, die in der Funktion (siehe ?function_name) vorgegeben ist:</p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">function_name</span><span class="op">(</span><span class="va">value1</span>, <span class="va">value2</span><span class="op">)</span></code></pre></div>
</div>
<div id="grundlegende-funktionen-in-r" class="section level3" number="3.5.9">
<h3>
<span class="header-section-number">3.5.9</span> Grundlegende Funktionen in R<a class="anchor" aria-label="anchor" href="#grundlegende-funktionen-in-r"><i class="fas fa-link"></i></a>
</h3>
<p>Es gibt ein paar wenige Befehle, die du immer wieder in R benötigst. Wir werden die Befehle anhand des Datensatzes <a href="data/human_resources.csv">human_resources</a> kennen lernen.</p>
<p>Zunächst müssen wir tidyverse laden und den Datensatz importieren:</p>
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="va">human_resources</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"human_resources.csv"</span><span class="op">)</span></code></pre></div>
<p>Mit <a href="https://www.rdocumentation.org/packages/utils/versions/3.6.1/topics/View">View</a>kannst du Dir den Datensatz in einem Excel-ähnlichen Format betrachten:</p>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/View.html">View</a></span><span class="op">(</span><span class="va">human_resources</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="images/02_grundlagen/view_hr.png" width="384"></div>
<p>Du kannst dir die Variablennamen mit der Funktion colnames ausgeben lassen:</p>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">human_resources</span><span class="op">)</span></code></pre></div>
<pre><code>##  [1] "id"                         "age"                       
##  [3] "department"                 "distance_from_home"        
##  [5] "education"                  "employee_count"            
##  [7] "gender"                     "job_role"                  
##  [9] "job_satisfaction"           "marital_status"            
## [11] "monthly_income"             "num_companies_worked"      
## [13] "performance_rating"         "total_working_years"       
## [15] "work_life_balance"          "years_at_company"          
## [17] "years_since_last_promotion"</code></pre>
<p>Manchmal möchte man wissen, wie viele Reihen in einem Datensatz stecken. Hierfür kannst du die Funktion <a href="https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/nrow">nrow</a>verwenden:</p>
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">human_resources</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 1470</code></pre>
<p>Genausogut lassen sich die Anzahl der Variablen (bzw. Spalten) in einem Datensatz mit der Funktion <a href="https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/nrow">ncol</a>ausgeben lassen:</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">human_resources</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 17</code></pre>
<p>Zuletzt benötigen wir noch die Funktion head. Mithilfe von head können wir uns die ersten Reihen eines Datensatzes ansehen:</p>
<div class="sourceCode" id="cb62"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">human_resources</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 17
##      id   age department      distance_from_ho~ education  employee_count gender
##   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                       &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
## 1     1    41 Sales                           1 College                 1 Female
## 2     2    49 Research &amp; Dev~                 8 Below Col~              1 Male  
## 3     3    37 Research &amp; Dev~                 2 College                 1 Male  
## 4     4    33 Research &amp; Dev~                 3 Master                  1 Female
## 5     5    27 Research &amp; Dev~                 2 Below Col~              1 Male  
## 6     6    32 Research &amp; Dev~                 2 College                 1 Male  
## # ... with 10 more variables: job_role &lt;chr&gt;, job_satisfaction &lt;chr&gt;,
## #   marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;, num_companies_worked &lt;dbl&gt;,
## #   performance_rating &lt;chr&gt;, total_working_years &lt;dbl&gt;,
## #   work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<div id="daten-exportieren" class="section level4" number="3.5.9.1">
<h4>
<span class="header-section-number">3.5.9.1</span> Daten exportieren<a class="anchor" aria-label="anchor" href="#daten-exportieren"><i class="fas fa-link"></i></a>
</h4>
<p>Wenn wir Daten importieren möchten, wollen wir sie auch exportieren können. Wir werden in diesem Kurs mehrmals Daten bereinigen und verändern und möchten diese Daten anschließend wieder in einer CSV-Datei speichern. Hierfür benutzen wir die <a href="https://readr.tidyverse.org/reference/write_delim.html"><em>write_csv</em></a>Funktion. Die Funktion <em>write_csv</em> hat zwei wichtige Argumente:</p>
<blockquote>
<p>Achte darauf, dass du die Funktion nur verwenden kannst, wenn du das Paket tidyverse geladen hast.</p>
</blockquote>
<div class="sourceCode" id="cb64"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://readr.tidyverse.org/reference/write_delim.html">write_csv</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">path</span><span class="op">)</span></code></pre></div>
<ul>
<li>x steht für den Datensatz, den wir der Funktion überführen.</li>
<li>path steht für den Dateinamen in denen wir die Datei speichern. Achte darauf, diesen Pfad immer mit Anführungsstrichen " zu umrunden.</li>
</ul>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://readr.tidyverse.org/reference/write_delim.html">write_csv</a></span><span class="op">(</span><span class="va">NAME_GEREINIGER_DATENSATZ</span>, <span class="st">"datensatz_gereinigt.csv"</span><span class="op">)</span></code></pre></div>
<blockquote>
<p>R speichert die Datei immer in das aktuelle Arbeitsverzeichnis. Diese kannst du verändern, indem du mit dem Shortcut STRG + Umschalt + H (für Mac COMMAND + Umschalt + H) das Arbeitsverzeichnis wechselt. In diesen Ordner wird die Datei anschließend gespeichert.</p>
</blockquote>
</div>
</div>
</div>
<div id="grundlagen-tidyverse" class="section level2" number="3.6">
<h2>
<span class="header-section-number">3.6</span> Grundlagen tidyverse<a class="anchor" aria-label="anchor" href="#grundlagen-tidyverse"><i class="fas fa-link"></i></a>
</h2>
<p>Tidyverse ist eine Sammlung an Paketen zur Datenanalyse, welche von <a href="http://hadley.nz/">Hadley Wickam</a>entwickelt wurde. Hadley Wickam ist Chief Data Scientist bei R-Studio und versucht mit der Entwicklung von tidyverse die Analyse von Daten in R zu vereinfachen. Alle Pakete haben eine einheitliche Philosophie und arbeiten reibungslos miteinander. Da tidyverse aktuell die beste Software zur Datenanalyse in R ist, verwenden wir dieses Paket.</p>
<p>Genauer werden wir in diesem Seminar tidyverse verwenden, um Daten zu bereinigen und zu visualisieren. Denn nicht immer liegen Daten in der Form vor, die wir für die Analyse der Daten benötigen. Bevor wir statistische Fragestellungen mit Jamovi berechnen, werden wir immer auf tidyverse zurück kommen, um unsere Daten in das Format zu bringen, welches wir für unsere Verfahren benötigen. Genauer gehen wir in diesem Seminar auf folgende Funktionen und Operatoren ein, die wir immer wieder verwenden:</p>
<ul>
<li>Der Pipe %&gt;% Operator</li>
<li>
<em>glimpse:</em> Variablen in einem Datensatz betrachten</li>
<li>
<em>count:</em> Diskrete Variablen zählen</li>
<li>
<em>select</em>: Variablen aus einem Datensatz selektieren</li>
<li>
<em>arrange:</em> Datensätze nach Variablen sortieren</li>
<li>
<em>filter:</em> Reihen aus einem Datensatz filtern</li>
<li>
<em>mutate:</em> Neue Variablen erstellen</li>
<li>Mehrere Befehle nacheinander ausführen</li>
</ul>
<blockquote>
<p><strong>Bevor du mit diesem Modul beginnst, stelle sicher, dass du das Paket tidyverse und den Datensatz <a href="data/human_resources.csv">human_resources.csv</a> geladen hast. Der Datensatz stammt von <a href="https://www.kaggle.com/pavansubhasht/ibm-hr-analytics-attrition-dataset">dieser Seite</a> und umfasst Daten über die Mitarbeitende einer fiktiven Firma. Unter anderem umfasst der Datensatz das Einkommen der Mitarbeitenden, ihre Entfernung zum Arbeitsort, ihre Position im Unternehmen und ihr Bildungsniveau</strong></p>
</blockquote>
<div id="der-pipe-operator" class="section level3" number="3.6.1">
<h3>
<span class="header-section-number">3.6.1</span> Der Pipe %&gt;% Operator<a class="anchor" aria-label="anchor" href="#der-pipe-operator"><i class="fas fa-link"></i></a>
</h3>
<p>Häufig führen wir nur eine Funktion aus, wenn wir einfache Berechnungen in R umsetzen möchten. Beispielsweise kann man mit einer Zeile den Mittelwert einer Variable berechnen. Was passiert allerdings, wenn wir mehrere Funktionen nacheinander ausführen müssen? Ein Beispiel: Stell Dir vor, du möchtest aus einem Vektor mit Zahlen den Mittelwert berechnen, aus dem Mittelwert anschließend die Wurzel ziehen und diesen Wert mit der Zahl 5 addieren. Dies wäre ein möglicher Lösungsweg:</p>
<div class="sourceCode" id="cb66"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">6</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>, <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 7.236068</code></pre>
<p>Dieser Code sieht nicht nur kompliziert aus, er ist es auch. Beispielsweise ist es schwer zu erkennen, welche Klammer zu welcher Funktion gehört. Alternativ könnten wir den Output der Funktionen (z.B. mean(c(4, 5, 6))) in Variablen speichern und die Berechnung sequentiell ausführen:</p>
<div class="sourceCode" id="cb68"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mittelwert</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">6</span><span class="op">)</span><span class="op">)</span>
<span class="va">wurzel</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">mittelwert</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">wurzel</span>, <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 7.236068</code></pre>
<p>Die Lösung ist bereits eleganter aber immer noch nicht perfekt, da wir Variablen erstellen, die wir später nicht mehr benötigen; wir möchten schließlich nur das Ergebnis wissen. Eine Alternative, dieses Problem zu lösen, ist der Pipe-Operator. Unser Problem der verschachtelten Funktionen können wir mit Hilfe des Pipe-Operators folgendermaßen lösen:</p>
<div class="sourceCode" id="cb70"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fl">5</span>, <span class="fl">6</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">.</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">.</span>, <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 7.236068</code></pre>
<p>Was ist hier passiert? Die Idee ist folgende: Jede Funktion nimmt Daten auf, verarbeitet diese und gibt diese weiter. Eine Analogie wären Fabriken. Die erste Fabrik fällt Holz und fertigt aus diesem Holz Bretter an. Das Holz ist der Input der Fabrik, Bretter der Output. Diese Bretter werden nun an die nächste Fabrik geschickt, welche anschließend die Bretter schleift. Die geschliffenen Bretter gehen anschließen an die Gitarrenbauerin, die aus ihnen eine Gitarre baut. Das Prinzip ist folgendes: Es gibt eine serielle Verarbeitung der Produkte. Genauso funktioniert der Pipe-Operator. Er übergibt den Output einer Funktion in die nächste Funktion. Hier ein weiteres Beispiel:</p>
<div class="sourceCode" id="cb72"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">9</span>, <span class="fl">10</span>, <span class="fl">8</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="va">.</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>Die Funktion mean(c(9, 10, 8)) berechnet den Mittelwert aus dem Vektor mit den Zahlen 9, 10, 8 (= 9). Diese Zahl 9 wird an die Funktion sqrt übergeben. Du siehst, dass in der Funktion sqrt(.) ein Punkt notiert ist. Dieser Punkt steht für den Output der vorherigen Funktion (hier mean -&gt; 9). Wir könnten diesen Punkt ebenso weglassen:</p>
<div class="sourceCode" id="cb74"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">9</span>, <span class="fl">10</span>, <span class="fl">8</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>Ein anderes Beispiel: Wir berechnen die Summe aus zwei Zahlen mit der Funktion sum. Die erste Zahl der Summe übergeben wir allerdings mithilfe des Pipe-Operators:</p>
<div class="sourceCode" id="cb76"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">3</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">.</span>, <span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>Alternativ können wir den Punkt . entfernen:</p>
<div class="sourceCode" id="cb78"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">3</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>Diese Befehle sind äquivalent zu folgendem Code:</p>
<div class="sourceCode" id="cb80"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>Der Vorteil des Pipe-Operators wird dir vermutlich erst im Verlaufe des Kurses deutlich, wenn wir mehrere Manipulationen an Daten vornehmen. An dieser Stelle sei gesagt, dass wir den Pipe-Operator immer wieder verwenden werden, da er die Lesbarkeit unseres Codes erhöht. In den nächsten Erklärungen wirst du sehen, weshalb der Operator so wichtig ist.</p>
<blockquote>
<p>Der Pipe Operator ist häufig schwierig mit der Tastatur zu schreiben. In R-Studio gibt es einen Shortcut um den Pipe-Operator einzufügen: Ctrl + Umschalt + M. Dies ist ein Shortcut, den es sich lohnt zu lernen.</p>
</blockquote>
</div>
<div id="grundlegende-tidyverse-befehle" class="section level3" number="3.6.2">
<h3>
<span class="header-section-number">3.6.2</span> Grundlegende tidyverse-Befehle<a class="anchor" aria-label="anchor" href="#grundlegende-tidyverse-befehle"><i class="fas fa-link"></i></a>
</h3>
<p>Es gibt ein paar Funktionen in der Datenanalyse, die wir immer wieder brauchen. Beispielsweise möchten wir häufig neue Variablen berechnen, bestimmte Reihen aus einem Datensatz filtern oder die Häufigkeit des Vorkommens bestimmter Werte zählen. Wir werden den Rest dieses Submoduls verbringen, diese Befehle kennen zu lernen. Im Verlaufe des Seminars wirst du diese Befehle immer wieder verwenden. Es ist daher ratsam, dass du dir diese Befehle gut einprägst.</p>
<div id="glimpse-variablen-in-einem-datensatz-ansehen" class="section level4" number="3.6.2.1">
<h4>
<span class="header-section-number">3.6.2.1</span> Glimpse: Variablen in einem Datensatz ansehen<a class="anchor" aria-label="anchor" href="#glimpse-variablen-in-einem-datensatz-ansehen"><i class="fas fa-link"></i></a>
</h4>
<p>In Excel sieht man die Daten jederzeit, in R nicht. Um einen Datensatz beispielsweise in R zu sehen, musst du ihn über die Konsole ausgeben lassen:</p>
<div class="sourceCode" id="cb82"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 17
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1     1    41 Sales                          1 College                 1 Female
##  2     2    49 Research &amp; De~                 8 Below Col~              1 Male  
##  3     3    37 Research &amp; De~                 2 College                 1 Male  
##  4     4    33 Research &amp; De~                 3 Master                  1 Female
##  5     5    27 Research &amp; De~                 2 Below Col~              1 Male  
##  6     6    32 Research &amp; De~                 2 College                 1 Male  
##  7     7    59 Research &amp; De~                 3 Bachelor                1 Female
##  8     8    30 Research &amp; De~                24 Below Col~              1 Male  
##  9     9    38 Research &amp; De~                23 Bachelor                1 Male  
## 10    10    36 Research &amp; De~                27 Bachelor                1 Male  
## # ... with 1,460 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Das funktioniert, allerdings wirst du nicht immer alle Variablen sehen können. Von den 17 Variablen in diesem Datensatz sind 9 nur namentlich erwähnt und du siehst nicht, was in den Variablen steckt. Eine Möglichkeit alle Variablen anzusehen ist die <a href="https://tibble.tidyverse.org/reference/glimpse.html">glimpse-Funktion</a>. Glimpse ordnet die Variablen in Reihen und nicht in Spalten an und erlaubt dir dadurch einen umfassenderen Einblick in die Daten:</p>
<div class="sourceCode" id="cb84"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">human_resources</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 1,470
## Columns: 17
## $ id                         &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, ~
## $ age                        &lt;dbl&gt; 41, 49, 37, 33, 27, 32, 59, 30, 38, 36, 35,~
## $ department                 &lt;chr&gt; "Sales", "Research &amp; Development", "Researc~
## $ distance_from_home         &lt;dbl&gt; 1, 8, 2, 3, 2, 2, 3, 24, 23, 27, 16, 15, 26~
## $ education                  &lt;chr&gt; "College", "Below College", "College", "Mas~
## $ employee_count             &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~
## $ gender                     &lt;chr&gt; "Female", "Male", "Male", "Female", "Male",~
## $ job_role                   &lt;chr&gt; "Sales Executive", "Research Scientist", "L~
## $ job_satisfaction           &lt;chr&gt; "Very High", "Medium", "High", "High", "Med~
## $ marital_status             &lt;chr&gt; "Single", "Married", "Single", "Married", "~
## $ monthly_income             &lt;dbl&gt; 5993, 5130, 2090, 2909, 3468, 3068, 2670, 2~
## $ num_companies_worked       &lt;dbl&gt; 8, 1, 6, 1, 9, 0, 4, 1, 0, 6, 0, 0, 1, 0, 5~
## $ performance_rating         &lt;chr&gt; "Excellent", "Outstanding", "Excellent", "E~
## $ total_working_years        &lt;dbl&gt; 8, 10, 7, 8, 6, 8, 12, 1, 10, 17, 6, 10, 5,~
## $ work_life_balance          &lt;chr&gt; "Bad", "Better", "Better", "Better", "Bette~
## $ years_at_company           &lt;dbl&gt; 6, 10, 0, 8, 2, 7, 1, 1, 9, 7, 5, 9, 5, 2, ~
## $ years_since_last_promotion &lt;dbl&gt; 0, 1, 0, 3, 2, 3, 0, 0, 1, 7, 0, 0, 4, 1, 0~</code></pre>
<p>Nun siehst du alle 17 Variablen des Datensatzes. Ebenso siehst du, dass der Datensatz 1470 Reihen enthält. Glimpse solltest du immer dann verwenden, wenn du sehen möchtest, welche Variablen ein Datensatz enthält und was in diesen Variablen drinsteckt.</p>
</div>
<div id="count-diskrete-variablen-zählen" class="section level4" number="3.6.2.2">
<h4>
<span class="header-section-number">3.6.2.2</span> <strong><em>count:</em></strong> <strong>Diskrete Variablen zählen</strong><a class="anchor" aria-label="anchor" href="#count-diskrete-variablen-z%C3%A4hlen"><i class="fas fa-link"></i></a>
</h4>
<p>Mit Hilfe von <a href="https://dplyr.tidyverse.org/reference/tally.html">count</a>können wir die Häufigkeit diskreter (nominalskalierter) Daten zählen. Beispielsweise können wir in unserem Datensatz prüfen, wie viele Männer und wie viele Frauen in der Firma arbeiten:</p>
<div class="sourceCode" id="cb86"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">gender</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 Female   588
## 2 Male     882</code></pre>
<p>Es gibt 588 Frauen und 882 Männer in dem Datensatz. Wie du siehst, habe ich den Pipe-Operator verwendet, um diese Häufigkeiten zu berechnen. In Worten sage ich folgendes: Nimm den Datensatz und übergib ihn als erstes Argument in die Funktion count.</p>
<p>Um zu verstehen, weshalb der Pipe-Operator für die Funktion count funktioniert, müssen wir uns nochmal ansehen, wie Funktionen funktionieren. Funktionen haben häufig Argumente, das heißt sie enthalten Informationen, mit denen sie Berechnungen ausführen. Schauen wir uns die Argumente der count-Funktion an. Wenn du count() in der Konsole tippst, erscheint folgender Hinweis:</p>
<div class="inline-figure"><img src="images/02_grundlagen/count.png" width="370"></div>
<p>Die ersten beiden Argumente der Funktion sind x und … x steht für einen Datensatz, die drei Punkte … für Variablen des Datensatzes (wenn du wissen möchtest, woher ich das weiß tippe ?count in der Konsole und schaube bei Help unter Arguments).</p>
<p>Wir hätten aus diesem Grund ebenso den Datensatz innerhalb der Funktion als Argument übergeben können und zudem die Variablen nennen können, für die wir die einzelnen Ausprägungen (z.B. Mann und Frau) zählen möchten:</p>
<div class="sourceCode" id="cb88"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">human_resources</span>, <span class="va">gender</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 Female   588
## 2 Male     882</code></pre>
<p>Wie du siehst, haben wir nun das erste Argument x explizit angegeben. Wir sagen R damit: “Bitte berechne mir die Häufigkeit der Ausprägungen der Variable gender für den Datensatz human_resources.”</p>
<div class="sourceCode" id="cb90"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">.</span>, <span class="va">gender</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 Female   588
## 2 Male     882</code></pre>
<p>Da der Pipe-Operator nichts anderes macht als Informationen von einer Funktion oder einem Befehl in eine andere Funktion zu übergeben, können wir nun den Datensatz in die Funktion count übergeben. Was der Pipe-Operator übergibt, wird immer mit einem Punkt (.) gekennzeichnet.</p>
<div class="sourceCode" id="cb92"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">.</span>, <span class="va">gender</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 Female   588
## 2 Male     882</code></pre>
<div class="sourceCode" id="cb94"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">gender</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   gender     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 Female   588
## 2 Male     882</code></pre>
<p>Da nun x das erste Argument der Funktion count ist, können wir es weglassen und nur den Punkt erwähnen. Ebenso können wir den Punkt weglassen und erhalten dennoch unseren Output.</p>
<p>Die Logik dieses Pipe-Operators gilt für alle nachfolgenden Funktionen. Versuche daher selbst einmal mit dem Pipe-Operator und dem count-Befehl zu spielen, um zu verstehen, wie der Pipe-Operator arbeitet.</p>
<p>Zuletzt können wir mit dem count-Befehl ebenso weitere, komplexere Fragen beantworten. Beispielsweise können wir uns fragen, welche Ausbildung Männer und Frauen haben. Im Datensatz gibt es eine Variable mit dem Namen education, in der der höchste Bildungsabschluss für jeden Mitarbeiter / jede Mitarbeiterin gespeichert ist:</p>
<div class="sourceCode" id="cb96"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">gender</span>, <span class="va">education</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 3
##    gender education         n
##    &lt;chr&gt;  &lt;chr&gt;         &lt;int&gt;
##  1 Female Bachelor        235
##  2 Female Below College    60
##  3 Female College         117
##  4 Female Doctor           22
##  5 Female Master          154
##  6 Male   Bachelor        337
##  7 Male   Below College   110
##  8 Male   College         165
##  9 Male   Doctor           26
## 10 Male   Master          244</code></pre>
<p>Beispielsweise kannst du erkennen, dass 22 Frauen einen Doktorabschluss haben. Bei den Männern sind es 26.</p>
<p>Im Grunde könntest du unendlich viele nominalskalierte Variablen in die Funktion count eintragen, allerdings würde dies unübersichtlich werden. In der Regel reichen eine oder zwei Variablen.</p>
</div>
<div id="select-variablen-aus-einem-datensatz-selektieren" class="section level4" number="3.6.2.3">
<h4>
<span class="header-section-number">3.6.2.3</span> <strong>select: Variablen aus einem Datensatz selektieren</strong><a class="anchor" aria-label="anchor" href="#select-variablen-aus-einem-datensatz-selektieren"><i class="fas fa-link"></i></a>
</h4>
<p>Datensätze haben manchmal viele Variablen. Um den Überblick zu behalten, können wir uns mit <a href="https://dplyr.tidyverse.org/reference/select.html">select</a>nur ein paar wenige Variablen ansehen. Zum Beispiel können wir aus unserem Datensatz nur die Variablen id und age selektieren:</p>
<div class="sourceCode" id="cb98"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">age</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 2
##       id   age
##    &lt;dbl&gt; &lt;dbl&gt;
##  1     1    41
##  2     2    49
##  3     3    37
##  4     4    33
##  5     5    27
##  6     6    32
##  7     7    59
##  8     8    30
##  9     9    38
## 10    10    36
## # ... with 1,460 more rows</code></pre>
<p>Der Aufbau der select-Funktion ist identisch mit den Funktionen glimpse und count. Das erste Argument ist der Datensatz, dann werden die Variablen aufgelistet, mit der die Funktion rechnen soll.</p>
<div class="sourceCode" id="cb100"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">age</span>, <span class="va">department</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 3
##       id   age department            
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                 
##  1     1    41 Sales                 
##  2     2    49 Research &amp; Development
##  3     3    37 Research &amp; Development
##  4     4    33 Research &amp; Development
##  5     5    27 Research &amp; Development
##  6     6    32 Research &amp; Development
##  7     7    59 Research &amp; Development
##  8     8    30 Research &amp; Development
##  9     9    38 Research &amp; Development
## 10    10    36 Research &amp; Development
## # ... with 1,460 more rows</code></pre>
<p>Beispielsweise könnten wir ebenso drei Variablen aus dem Datensatz selektieren.</p>
<blockquote>
<p>Im Übrigen. Wenn du dich fragt, woher man weiß, welche Variablen in einem Dtensatz sind. Mit der glimpse-Funktion kannst du dir die Variablennamen in einem Datensatz immer wieder ansehen.</p>
</blockquote>
<p>Manchmal wollen wir allerdings genau das Gegenteil. Variablen aus einem Datensatz entfernen. Dies können wir mit select erreichen, indem wir ein Minus vor die Variable setzen, die wir entfernen möchten:</p>
<div class="sourceCode" id="cb102"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">gender</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 16
##       id   age department   distance_from_ho~ education employee_count job_role 
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                    &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;    
##  1     1    41 Sales                        1 College                1 Sales Ex~
##  2     2    49 Research &amp; ~                 8 Below Co~              1 Research~
##  3     3    37 Research &amp; ~                 2 College                1 Laborato~
##  4     4    33 Research &amp; ~                 3 Master                 1 Research~
##  5     5    27 Research &amp; ~                 2 Below Co~              1 Laborato~
##  6     6    32 Research &amp; ~                 2 College                1 Laborato~
##  7     7    59 Research &amp; ~                 3 Bachelor               1 Laborato~
##  8     8    30 Research &amp; ~                24 Below Co~              1 Laborato~
##  9     9    38 Research &amp; ~                23 Bachelor               1 Manufact~
## 10    10    36 Research &amp; ~                27 Bachelor               1 Healthca~
## # ... with 1,460 more rows, and 9 more variables: job_satisfaction &lt;chr&gt;,
## #   marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;, num_companies_worked &lt;dbl&gt;,
## #   performance_rating &lt;chr&gt;, total_working_years &lt;dbl&gt;,
## #   work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Oder, stell dir vor, du möchtest mehrere Variablen aus dem Datensatz entfernen, die beieinander liegen. Nehmen wir beispielsweise an, du möchtest die Variablen education bis monthly_income aus dem Datensatz selektieren, welche laut dem glimpse-Befehl hintereinander stehen:</p>
<div class="sourceCode" id="cb104"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://pillar.r-lib.org/reference/glimpse.html">glimpse</a></span><span class="op">(</span><span class="va">human_resources</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 1,470
## Columns: 17
## $ id                         &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, ~
## $ age                        &lt;dbl&gt; 41, 49, 37, 33, 27, 32, 59, 30, 38, 36, 35,~
## $ department                 &lt;chr&gt; "Sales", "Research &amp; Development", "Researc~
## $ distance_from_home         &lt;dbl&gt; 1, 8, 2, 3, 2, 2, 3, 24, 23, 27, 16, 15, 26~
## $ education                  &lt;chr&gt; "College", "Below College", "College", "Mas~
## $ employee_count             &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~
## $ gender                     &lt;chr&gt; "Female", "Male", "Male", "Female", "Male",~
## $ job_role                   &lt;chr&gt; "Sales Executive", "Research Scientist", "L~
## $ job_satisfaction           &lt;chr&gt; "Very High", "Medium", "High", "High", "Med~
## $ marital_status             &lt;chr&gt; "Single", "Married", "Single", "Married", "~
## $ monthly_income             &lt;dbl&gt; 5993, 5130, 2090, 2909, 3468, 3068, 2670, 2~
## $ num_companies_worked       &lt;dbl&gt; 8, 1, 6, 1, 9, 0, 4, 1, 0, 6, 0, 0, 1, 0, 5~
## $ performance_rating         &lt;chr&gt; "Excellent", "Outstanding", "Excellent", "E~
## $ total_working_years        &lt;dbl&gt; 8, 10, 7, 8, 6, 8, 12, 1, 10, 17, 6, 10, 5,~
## $ work_life_balance          &lt;chr&gt; "Bad", "Better", "Better", "Better", "Bette~
## $ years_at_company           &lt;dbl&gt; 6, 10, 0, 8, 2, 7, 1, 1, 9, 7, 5, 9, 5, 2, ~
## $ years_since_last_promotion &lt;dbl&gt; 0, 1, 0, 3, 2, 3, 0, 0, 1, 7, 0, 0, 4, 1, 0~</code></pre>
<div class="sourceCode" id="cb106"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">education</span><span class="op">:</span><span class="va">monthly_income</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 7
##    education  employee_count gender job_role     job_satisfaction marital_status
##    &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;        &lt;chr&gt;            &lt;chr&gt;         
##  1 College                 1 Female Sales Execu~ Very High        Single        
##  2 Below Col~              1 Male   Research Sc~ Medium           Married       
##  3 College                 1 Male   Laboratory ~ High             Single        
##  4 Master                  1 Female Research Sc~ High             Married       
##  5 Below Col~              1 Male   Laboratory ~ Medium           Married       
##  6 College                 1 Male   Laboratory ~ Very High        Single        
##  7 Bachelor                1 Female Laboratory ~ Low              Married       
##  8 Below Col~              1 Male   Laboratory ~ High             Divorced      
##  9 Bachelor                1 Male   Manufacturi~ High             Single        
## 10 Bachelor                1 Male   Healthcare ~ High             Married       
## # ... with 1,460 more rows, and 1 more variable: monthly_income &lt;dbl&gt;</code></pre>
<p>Um diese Variablen aus dem Datensatz zu selektieren, musst du die erste und die letzte Variable benennen und mit einem Doppelpunkt trennen.</p>
<div class="sourceCode" id="cb108"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="op">(</span><span class="va">education</span><span class="op">:</span><span class="va">monthly_income</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 10
##       id   age department    distance_from_ho~ num_companies_w~ performance_rat~
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt;            &lt;dbl&gt; &lt;chr&gt;           
##  1     1    41 Sales                         1                8 Excellent       
##  2     2    49 Research &amp; D~                 8                1 Outstanding     
##  3     3    37 Research &amp; D~                 2                6 Excellent       
##  4     4    33 Research &amp; D~                 3                1 Excellent       
##  5     5    27 Research &amp; D~                 2                9 Excellent       
##  6     6    32 Research &amp; D~                 2                0 Excellent       
##  7     7    59 Research &amp; D~                 3                4 Outstanding     
##  8     8    30 Research &amp; D~                24                1 Outstanding     
##  9     9    38 Research &amp; D~                23                0 Outstanding     
## 10    10    36 Research &amp; D~                27                6 Excellent       
## # ... with 1,460 more rows, and 4 more variables: total_working_years &lt;dbl&gt;,
## #   work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Möchtest du hingegen, dass genau diese Variablen aus dem Datensatz entfernt werden, musst du die Variablen mit einer Klammer umschließen und ein - davor schreiben.</p>
</div>
<div id="arrange-datensätze-nach-variablen-sortieren" class="section level4" number="3.6.2.4">
<h4>
<span class="header-section-number">3.6.2.4</span> arrange: Datensätze nach Variablen sortieren<a class="anchor" aria-label="anchor" href="#arrange-datens%C3%A4tze-nach-variablen-sortieren"><i class="fas fa-link"></i></a>
</h4>
<p>Stell dir vor, du möchtest wissen, wer die ältesten Mitarbeitende in der Firma sind. In Excel würdest du hierfür den Datensatz nach dem Alter der Mitarbeitenden sortieren. In tidyverse kannst du das gleiche mit der Funktion arrange schaffen:</p>
<div class="sourceCode" id="cb110"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 17
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1   297    18 Research &amp; De~                 3 Bachelor                1 Male  
##  2   302    18 Sales                         10 Bachelor                1 Female
##  3   458    18 Sales                          5 Bachelor                1 Male  
##  4   728    18 Research &amp; De~                 5 College                 1 Male  
##  5   829    18 Research &amp; De~                 8 Below Col~              1 Male  
##  6   973    18 Research &amp; De~                 1 Bachelor                1 Female
##  7  1154    18 Sales                          3 College                 1 Female
##  8  1312    18 Research &amp; De~                14 Bachelor                1 Female
##  9   128    19 Sales                         22 Below Col~              1 Male  
## 10   150    19 Research &amp; De~                 3 Below Col~              1 Female
## # ... with 1,460 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Wie du siehst sind die Mitarbeitenden von jung nach alt sortiert. Dich interessieren allerdings die älteren Mitarbeitende. Hierfür müssen wir arrange zusätzlich sagen, dass die Variable von hoch nach niedrig angezeigt wird.</p>
<div class="sourceCode" id="cb112"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 17
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1   412    60 Research &amp; De~                 7 Bachelor                1 Female
##  2   428    60 Sales                         28 Bachelor                1 Female
##  3   537    60 Sales                         16 Master                  1 Male  
##  4   880    60 Sales                          7 Master                  1 Male  
##  5  1210    60 Research &amp; De~                 1 Master                  1 Male  
##  6     7    59 Research &amp; De~                 3 Bachelor                1 Female
##  7    64    59 Sales                         25 Bachelor                1 Female
##  8    71    59 Sales                          1 Below Col~              1 Female
##  9   106    59 Human Resourc~                 2 Master                  1 Female
## 10   226    59 Research &amp; De~                 3 Bachelor                1 Male  
## # ... with 1,460 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Nun siehst du, dass die ältesten Mitarbeitende 60 Jahre alt sind. Ebenso erkennst du, dass die Mitarbeitende von alt nach jung sortiert sind.</p>
<p>Wir können aber genausogut zwei Variablen sortieren. Die Reihenfolge der Variablen, die wir in die Funktion arrange eingeben, gibt an, welche Variable zuerst sortiert wird. Zum Beispiel können diejenigen Mitarbeitende innerhalb eines Alters (z.B. alle 60 Jahre alt) nach der Distanz sortieren, die sie zur Arbeit fahren müssen:</p>
<div class="sourceCode" id="cb114"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span>, <span class="va">distance_from_home</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 17
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1  1210    60 Research &amp; De~                 1 Master                  1 Male  
##  2   412    60 Research &amp; De~                 7 Bachelor                1 Female
##  3   880    60 Sales                          7 Master                  1 Male  
##  4   537    60 Sales                         16 Master                  1 Male  
##  5   428    60 Sales                         28 Bachelor                1 Female
##  6    71    59 Sales                          1 Below Col~              1 Female
##  7   759    59 Sales                          1 College                 1 Male  
##  8   106    59 Human Resourc~                 2 Master                  1 Female
##  9   744    59 Research &amp; De~                 2 Bachelor                1 Female
## 10     7    59 Research &amp; De~                 3 Bachelor                1 Female
## # ... with 1,460 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Wie du siehst sind die Mitarbeitende, welche 60 Jahre alt sind, nun danach sortiert, wie weit sie von dem Arbeitsplatz entfernt wohnen. Der Mitarbeiter mit der id 1210 beispielsweise wohnt nur einen Kilometer vom Arbeitsplatz entfernt, die Mitarbeitende mit der id 428 wohnt 28 Kilometer.</p>
</div>
<div id="filter-reihen-aus-einem-datensatz-filtern" class="section level4" number="3.6.2.5">
<h4>
<span class="header-section-number">3.6.2.5</span> filter: Reihen aus einem Datensatz filtern<a class="anchor" aria-label="anchor" href="#filter-reihen-aus-einem-datensatz-filtern"><i class="fas fa-link"></i></a>
</h4>
<p>Eine weitere häufige Funktion ist das Filtern von Daten. Stell dir beispielsweise vor, du möchtest alle Männer aus dem Datensatz entfernen. Das heißt, jede Reihe bzw. Person, für die in der Variable gender Male steht, soll aus dem Datensatz entfernt werden. Dies können wir mit <a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a> erreichen:</p>
<div class="sourceCode" id="cb116"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">gender</span> <span class="op">!=</span> <span class="st">"Male"</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 588 x 17
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1     1    41 Sales                          1 College                 1 Female
##  2     4    33 Research &amp; De~                 3 Master                  1 Female
##  3     7    59 Research &amp; De~                 3 Bachelor                1 Female
##  4    12    29 Research &amp; De~                15 College                 1 Female
##  5    16    29 Research &amp; De~                21 Master                  1 Female
##  6    19    53 Sales                          2 Master                  1 Female
##  7    21    24 Research &amp; De~                11 College                 1 Female
##  8    23    34 Research &amp; De~                 7 Master                  1 Female
##  9    26    53 Research &amp; De~                 5 Bachelor                1 Female
## 10    27    32 Research &amp; De~                16 Below Col~              1 Female
## # ... with 578 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Die Funktion lässt sich am besten verstehen, wenn wir die Operatoren ==, !=, &gt;, &lt; und %in% im einzelnen durchgehen. Beginnen wir mit dem Operator !=. != steht für “ist nicht.” In unserem Beispiel haben wir tidyverse gesagt: “Behalte alle Reihen, in der die Variable gender nicht”Male" ist.</p>
<p>Etwas einfacher sehen wir den gleichen Effekt, wenn wir uns fragen, ob zwei Zahlen gleich oder verschieden ist. Du weißt, dass 3 nicht 4 ist (TRUE). Du weißt ebenso, dass die Aussage 3 ist nicht 3 falsch ist (FALSE). Ebenso würdest du zustimmen, wenn ich sage 4 ist gleich 4 (TRUE). Wenn ich aber sage, dass 3 gleich 4 ist würdest du sagen, dass ist falsch (FALSE).</p>
<div class="sourceCode" id="cb118"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">3</span> <span class="op">!=</span> <span class="fl">4</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb120"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">3</span> <span class="op">!=</span> <span class="fl">3</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb122"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">4</span> <span class="op">==</span> <span class="fl">4</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb124"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fl">3</span> <span class="op">==</span> <span class="fl">4</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>Auf Variablen übertragen fragen wir uns bei der Funktion filter immer, ob die Ausprägung einer Variable gleich oder ungleich eines bestimmten Wertes ist. Diejenigen Berechnungen, die TRUE ergeben, werden behalten, diejenigen, die FALSE ergeben, werden aus dem Datensatz entfernt. Wenn ich demnach sage gender != “Male” entferne ich alle Reihen, in denen die Ausprägung der Variable gender “Male” ist.</p>
<blockquote>
<p>Wenn du übrigens nicht weißt, welche Ausprägungen es für eine Variable gibt, kannst du diese mit der count-Funktion finden: z.B. count(human_resources, gender)</p>
</blockquote>
<p>Mit dem Wissen um TRUE und FALSE können wir komplexere Berechnungen mit filter durchführen. Zum Beispiel möchten wir nur Mitarbeitende in dem Datensatz behalten, die älter als 50 Jahre sind.</p>
<div class="sourceCode" id="cb126"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">age</span> <span class="op">&gt;</span> <span class="fl">50</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 143 x 17
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1     7    59 Research &amp; De~                 3 Bachelor                1 Female
##  2    19    53 Sales                          2 Master                  1 Female
##  3    26    53 Research &amp; De~                 5 Bachelor                1 Female
##  4    64    59 Sales                         25 Bachelor                1 Female
##  5    66    55 Research &amp; De~                 8 Bachelor                1 Female
##  6    71    59 Sales                          1 Below Col~              1 Female
##  7    83    55 Sales                          1 College                 1 Male  
##  8    86    56 Research &amp; De~                 7 Bachelor                1 Male  
##  9    88    51 Research &amp; De~                 9 Master                  1 Male  
## 10    92    51 Sales                         21 Master                  1 Male  
## # ... with 133 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Wie du siehst, hat der Datensatz nur noch 143 Mitarbeitende. Zwar haben wir in diesem Beispiel nicht den Operator != oder ==, sondern den Operator &gt; verwendet. Dennoch gibt uns die Aussage age &gt; 50 einen wahren Wert (TRUE) oder einen falschen Wert (FALSE) zurück. Wer beispielsweise 30 Jahre alt ist, wird nicht in den Datensatz übernommen (30 &gt; 50 -&gt; FALSE). Eine Mitarbeiterin, die 52 Jahre alt ist, wird in den Datensatz übernommen (52 &gt; 50 -&gt; TRUE).</p>
<p>Manchmal möchten wir allerdings mehrere Zeilen gleichzeitig aus einem Datensatz entfernen beziehungsweise behalten. Stell dir vor, wir möchten alle Mitarbeitende aus dem Datensatz filtern, die über 50 Jahre sind und die weiblich sind. Hierfür haben wir zwei Möglichkeiten:</p>
<div class="sourceCode" id="cb128"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">age</span> <span class="op">&gt;</span> <span class="fl">50</span> <span class="op">&amp;</span> <span class="va">gender</span> <span class="op">==</span> <span class="st">"Female"</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 64 x 17
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1     7    59 Research &amp; De~                 3 Bachelor                1 Female
##  2    19    53 Sales                          2 Master                  1 Female
##  3    26    53 Research &amp; De~                 5 Bachelor                1 Female
##  4    64    59 Sales                         25 Bachelor                1 Female
##  5    66    55 Research &amp; De~                 8 Bachelor                1 Female
##  6    71    59 Sales                          1 Below Col~              1 Female
##  7    96    54 Research &amp; De~                 2 Master                  1 Female
##  8   106    59 Human Resourc~                 2 Master                  1 Female
##  9   111    51 Research &amp; De~                 1 Master                  1 Female
## 10   113    54 Human Resourc~                26 Bachelor                1 Female
## # ... with 54 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb130"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">age</span> <span class="op">&gt;</span> <span class="fl">50</span>, <span class="va">gender</span> <span class="op">==</span> <span class="st">"Female"</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 64 x 17
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1     7    59 Research &amp; De~                 3 Bachelor                1 Female
##  2    19    53 Sales                          2 Master                  1 Female
##  3    26    53 Research &amp; De~                 5 Bachelor                1 Female
##  4    64    59 Sales                         25 Bachelor                1 Female
##  5    66    55 Research &amp; De~                 8 Bachelor                1 Female
##  6    71    59 Sales                          1 Below Col~              1 Female
##  7    96    54 Research &amp; De~                 2 Master                  1 Female
##  8   106    59 Human Resourc~                 2 Master                  1 Female
##  9   111    51 Research &amp; De~                 1 Master                  1 Female
## 10   113    54 Human Resourc~                26 Bachelor                1 Female
## # ... with 54 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Einerseits können wir die Aussagen mit einem Komma trennen, andererseits können wir ein &amp; (und) dazwischen setzen. Beide Varianten behalten nur diejenigen Mitarbeiterinnen, die über 50 sind und weiblich sind.</p>
<p>Das Gegenteil wären Mitarbeitende, die entweder über 50 Jahre alt sind oder weiblich sind. Hierfür verwenden wir den | (oder) Operator:</p>
<div class="sourceCode" id="cb132"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">age</span> <span class="op">&gt;</span> <span class="fl">50</span> <span class="op">|</span> <span class="va">gender</span> <span class="op">==</span> <span class="st">"Female"</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 667 x 17
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1     1    41 Sales                          1 College                 1 Female
##  2     4    33 Research &amp; De~                 3 Master                  1 Female
##  3     7    59 Research &amp; De~                 3 Bachelor                1 Female
##  4    12    29 Research &amp; De~                15 College                 1 Female
##  5    16    29 Research &amp; De~                21 Master                  1 Female
##  6    19    53 Sales                          2 Master                  1 Female
##  7    21    24 Research &amp; De~                11 College                 1 Female
##  8    23    34 Research &amp; De~                 7 Master                  1 Female
##  9    26    53 Research &amp; De~                 5 Bachelor                1 Female
## 10    27    32 Research &amp; De~                16 Below Col~              1 Female
## # ... with 657 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Du siehst, dass der Datensatz nun 667 Mitarbeitende enthält. Bei unserem vorherigen und-Befehl waren es 64 Mitarbeitende.</p>
<p>Stell dir weiterhin vor, du möchtest alle Mitarbeitende aus dem Datensatz filtern, die entweder einen Bachelor- oder Masterabschluss haben. Momentan können wir diese Frage mit dem Oder-Operator (|) beantworten. Es geht allerdings eleganter mit dem %in%-Operator:</p>
<div class="sourceCode" id="cb134"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">education</span> <span class="op">==</span> <span class="st">"Bachelor"</span> <span class="op">|</span> <span class="va">education</span> <span class="op">==</span> <span class="st">"Master"</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 970 x 17
##       id   age department       distance_from_h~ education employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                       &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt; 
##  1     4    33 Research &amp; Deve~                3 Master                 1 Female
##  2     7    59 Research &amp; Deve~                3 Bachelor               1 Female
##  3     9    38 Research &amp; Deve~               23 Bachelor               1 Male  
##  4    10    36 Research &amp; Deve~               27 Bachelor               1 Male  
##  5    11    35 Research &amp; Deve~               16 Bachelor               1 Male  
##  6    15    28 Research &amp; Deve~               24 Bachelor               1 Male  
##  7    16    29 Research &amp; Deve~               21 Master                 1 Female
##  8    19    53 Sales                           2 Master                 1 Female
##  9    20    38 Research &amp; Deve~                2 Bachelor               1 Male  
## 10    22    36 Sales                           9 Master                 1 Male  
## # ... with 960 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb136"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">education</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Bachelor"</span>, <span class="st">"Master"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 970 x 17
##       id   age department       distance_from_h~ education employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                       &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt; 
##  1     4    33 Research &amp; Deve~                3 Master                 1 Female
##  2     7    59 Research &amp; Deve~                3 Bachelor               1 Female
##  3     9    38 Research &amp; Deve~               23 Bachelor               1 Male  
##  4    10    36 Research &amp; Deve~               27 Bachelor               1 Male  
##  5    11    35 Research &amp; Deve~               16 Bachelor               1 Male  
##  6    15    28 Research &amp; Deve~               24 Bachelor               1 Male  
##  7    16    29 Research &amp; Deve~               21 Master                 1 Female
##  8    19    53 Sales                           2 Master                 1 Female
##  9    20    38 Research &amp; Deve~                2 Bachelor               1 Male  
## 10    22    36 Sales                           9 Master                 1 Male  
## # ... with 960 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Beide Befehle kommen zu dem gleichen Ergebnis. Die Variante mit dem %in%-Operator ist allerdings kürzer und daher zu bevorzugen. Diese Variante eignet sich beispielsweise auch, um Probanden mit einer bestimmten ID aus einem Datensatz zu entfernen.</p>
</div>
<div id="mutate-neue-variablen-berechnen" class="section level4" number="3.6.2.6">
<h4>
<span class="header-section-number">3.6.2.6</span> mutate: Neue Variablen berechnen<a class="anchor" aria-label="anchor" href="#mutate-neue-variablen-berechnen"><i class="fas fa-link"></i></a>
</h4>
<p>Manchmal möchten wir neue Variablen aus einem Datensatz berechnen. Stell dir vor, du möchtest das Einkommen der Mitarbeitenden von Dollar in Euro umrechnen. Oder, du möchtest aus dem monatlichen Einkommen der Mitarbeiter, das Jahreseinkommen berechnen. Diese Berechnungen kannst du mit dem <a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a> Befehl umsetzen. Berechnen wir einmal das Jahreseinkommen der Mitarbeitenden:</p>
<div class="sourceCode" id="cb138"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>
    yearly_income <span class="op">=</span> <span class="va">monthly_income</span> <span class="op">*</span> <span class="fl">12</span>
  <span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 18
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1     1    41 Sales                          1 College                 1 Female
##  2     2    49 Research &amp; De~                 8 Below Col~              1 Male  
##  3     3    37 Research &amp; De~                 2 College                 1 Male  
##  4     4    33 Research &amp; De~                 3 Master                  1 Female
##  5     5    27 Research &amp; De~                 2 Below Col~              1 Male  
##  6     6    32 Research &amp; De~                 2 College                 1 Male  
##  7     7    59 Research &amp; De~                 3 Bachelor                1 Female
##  8     8    30 Research &amp; De~                24 Below Col~              1 Male  
##  9     9    38 Research &amp; De~                23 Bachelor                1 Male  
## 10    10    36 Research &amp; De~                27 Bachelor                1 Male  
## # ... with 1,460 more rows, and 11 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;, yearly_income &lt;dbl&gt;</code></pre>
<p>Zunächst musst du den Namen der neuen Variable linksseitig nennen (yearly_income). Anschließend folgt ein =. Hinter dem = schreibst du auf, wie die Variable berechnet wird. In diesem Fall haben wir das monatliche Einkommen mal 12 berechnet, da ein Jahr 12 Monate hat.</p>
<p>Ein anders Beispiel. Stell dir vor, wir möchten eine Variable erstellen, die anzeigt, ob eine Mitarbeiterin / ein Mitarbeiter mehr oder weniger als das Jahreseinkommen verdient:</p>
<div class="sourceCode" id="cb140"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>
    yearly_income        <span class="op">=</span> <span class="va">monthly_income</span> <span class="op">*</span> <span class="fl">12</span>,
    salary_above_average <span class="op">=</span> <span class="va">yearly_income</span> <span class="op">&gt;</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">yearly_income</span><span class="op">)</span>
  <span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1,470 x 19
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1     1    41 Sales                          1 College                 1 Female
##  2     2    49 Research &amp; De~                 8 Below Col~              1 Male  
##  3     3    37 Research &amp; De~                 2 College                 1 Male  
##  4     4    33 Research &amp; De~                 3 Master                  1 Female
##  5     5    27 Research &amp; De~                 2 Below Col~              1 Male  
##  6     6    32 Research &amp; De~                 2 College                 1 Male  
##  7     7    59 Research &amp; De~                 3 Bachelor                1 Female
##  8     8    30 Research &amp; De~                24 Below Col~              1 Male  
##  9     9    38 Research &amp; De~                23 Bachelor                1 Male  
## 10    10    36 Research &amp; De~                27 Bachelor                1 Male  
## # ... with 1,460 more rows, and 12 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;, yearly_income &lt;dbl&gt;,
## #   salary_above_average &lt;lgl&gt;</code></pre>
<p>Drei Dinge lernen wir aus diesem Beispiel.</p>
<ol style="list-style-type: decimal">
<li>Zunächst siehst du, dass du mehrere neue Variablen gleichzeitig berechnen kannst. In diesem Beispiel haben wir sowohl die Variable yearly_income als auch salary_above_average berechnet.</li>
<li>Ebenso kannst du erkennen, dass wir eine neue Variable direkt verwenden können, um eine weitere Variable zu berechnen. Beispielsweise haben wir die Variable yearly_income im ersten Schritt erzeugt und im zweiten Schritt zur Berechnung der Variable salary_above_average verwendet.</li>
<li>Zuletzt erkennst du, dass wir zur Berechnung der Variable salary_above_average die Funktion mean verwendet haben. Vermutlich ist deine Annahme, dass der Mittelwert nur berechnet werden kann, wenn auch der Datensatz vorher angegeben wird. Zum Beispiel: mean(human_resources$yearly_income). Innerhalb der tidyverse-Funktionen musst du den Datensatz allerdings nie angeben, sondern kannst lediglich die Variablennamen angeben. Aus diesem Grund funktioniert der mean-Befehl an dieser Stelle.</li>
</ol>
</div>
</div>
<div id="mehrere-befehle-nacheinander-ausführen" class="section level3" number="3.6.3">
<h3>
<span class="header-section-number">3.6.3</span> Mehrere Befehle nacheinander ausführen<a class="anchor" aria-label="anchor" href="#mehrere-befehle-nacheinander-ausf%C3%BChren"><i class="fas fa-link"></i></a>
</h3>
<p>Mit diesen Befehlen können wir bereits recht komplexere Operationen an Datensätzen ausführen. Nur, bei einem Befehl bleibt es selten, häufig möchten wir mehrere dieser Befehle nacheinander ausführen. Nur wie?</p>
<p>Der Trick besteht darin, mehrere dieser Befehle mit dem Pipe-Operator zusammen zu führen. Nehmen wir ein Beispiel: Du möchtest aus dem Datensatz alle Frauen filtern und anschließend prüfen, welchen Bildungsabschluss die Frauen in dem Unternehmen haben:</p>
<div class="sourceCode" id="cb142"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">gender</span> <span class="op">==</span> <span class="st">"Female"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">education</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   education         n
##   &lt;chr&gt;         &lt;int&gt;
## 1 Bachelor        235
## 2 Below College    60
## 3 College         117
## 4 Doctor           22
## 5 Master          154</code></pre>
<p>Wie du siehst, habe ich zunächst den Datensatz nach den Frauen gefiltert und anschließend gezählt, welcher Bildungsabschluss unter den Frauen wie häufig auftritt. Vlt. möchest du die Häufigkeit zusätzlich sortieren?</p>
<div class="sourceCode" id="cb144"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">gender</span> <span class="op">==</span> <span class="st">"Female"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">education</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">n</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   education         n
##   &lt;chr&gt;         &lt;int&gt;
## 1 Bachelor        235
## 2 Master          154
## 3 College         117
## 4 Below College    60
## 5 Doctor           22</code></pre>
<p>Wie du siehst, haben wir nun zusätzlich die Funktion arrange verwendet, um die Häufigkeit von hoch nach niedrig zu sortieren. Die meisten Frauen in der Firma haben offensichtlich einen Bachelor-Abschluss.</p>
<p>Oder, stell dir vor, du möchtest wissen, welche Mitarbeitende besonders weit von der Arbeitsstelle wohnen, um ihnen evtl. die Möglichkeit für zusätzliche Home-Office Tage zu geben. Dabei interessiert dich das Alter der Mitarbeitenden, deren id und deren Distanz zum Arbeitsort:</p>
<div class="sourceCode" id="cb146"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">distance_from_home</span> <span class="op">&gt;</span> <span class="fl">25</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">age</span>, <span class="va">distance_from_home</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 87 x 3
##       id   age distance_from_home
##    &lt;dbl&gt; &lt;dbl&gt;              &lt;dbl&gt;
##  1    10    36                 27
##  2    13    31                 26
##  3    62    38                 29
##  4   113    54                 26
##  5   120    43                 26
##  6   131    43                 28
##  7   139    25                 28
##  8   142    45                 29
##  9   151    40                 26
## 10   182    34                 27
## # ... with 77 more rows</code></pre>
<p>Insgesamt wohnen 25 Mitarbeitende mehr als 25 Kilometer vom Arbeitsort entfernt. Wer wohnt eigentlich am weitesten entfernt?</p>
<div class="sourceCode" id="cb148"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">distance_from_home</span> <span class="op">&gt;</span> <span class="fl">25</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">age</span>, <span class="va">distance_from_home</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">distance_from_home</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 87 x 3
##       id   age distance_from_home
##    &lt;dbl&gt; &lt;dbl&gt;              &lt;dbl&gt;
##  1    62    38                 29
##  2   142    45                 29
##  3   200    38                 29
##  4   205    38                 29
##  5   260    31                 29
##  6   272    47                 29
##  7   353    48                 29
##  8   410    42                 29
##  9   425    57                 29
## 10   426    50                 29
## # ... with 77 more rows</code></pre>
<p>Es sind mehrere Personen, mit einer Distanz von 29 Kilometer. Und wie alt ist die älteste Person, die so weit zur Arbeit fahren muss?</p>
<div class="sourceCode" id="cb150"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">distance_from_home</span> <span class="op">&gt;</span> <span class="fl">25</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">age</span>, <span class="va">distance_from_home</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">distance_from_home</span><span class="op">)</span>, <span class="fu"><a href="https://dplyr.tidyverse.org/reference/desc.html">desc</a></span><span class="op">(</span><span class="va">age</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 87 x 3
##       id   age distance_from_home
##    &lt;dbl&gt; &lt;dbl&gt;              &lt;dbl&gt;
##  1   425    57                 29
##  2  1435    52                 29
##  3   426    50                 29
##  4   353    48                 29
##  5   272    47                 29
##  6   142    45                 29
##  7  1038    45                 29
##  8   876    44                 29
##  9   410    42                 29
## 10   605    42                 29
## # ... with 77 more rows</code></pre>
<p>57 Jahre alt. Wie du siehst, können wir mit diesen Befehlen bereits sehr schnell Fragen an den Datensatz beantworten. Tidyverse hat noch eine Vielzahl an Funktionen, mit denen wir noch viel komplexere Berechnungen ausführen können (siehe <a href="https://www.tidyverse.org/">tidyverse</a>). Für diesen Kurs beschränken wir uns auf diese zentralen Funktionen und werden diese immer wieder in diesem Kurs verwenden.</p>
<p>Solange du den Output dieser Funktionen nicht speicherst, geht er verloren. Stell dir vor, du möchtest einen neuen Datensatz speichern, der nur die weiblichen Mitarbeiterinnen enthält. Diese Variante würde zwar die Berechnungen ausführen, allerdings den Datensatz nicht dauerhaft speichern:</p>
<div class="sourceCode" id="cb152"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">gender</span> <span class="op">==</span> <span class="st">"Female"</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 588 x 17
##       id   age department     distance_from_ho~ education  employee_count gender
##    &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt; &lt;chr&gt;               &lt;dbl&gt; &lt;chr&gt; 
##  1     1    41 Sales                          1 College                 1 Female
##  2     4    33 Research &amp; De~                 3 Master                  1 Female
##  3     7    59 Research &amp; De~                 3 Bachelor                1 Female
##  4    12    29 Research &amp; De~                15 College                 1 Female
##  5    16    29 Research &amp; De~                21 Master                  1 Female
##  6    19    53 Sales                          2 Master                  1 Female
##  7    21    24 Research &amp; De~                11 College                 1 Female
##  8    23    34 Research &amp; De~                 7 Master                  1 Female
##  9    26    53 Research &amp; De~                 5 Bachelor                1 Female
## 10    27    32 Research &amp; De~                16 Below Col~              1 Female
## # ... with 578 more rows, and 10 more variables: job_role &lt;chr&gt;,
## #   job_satisfaction &lt;chr&gt;, marital_status &lt;chr&gt;, monthly_income &lt;dbl&gt;,
## #   num_companies_worked &lt;dbl&gt;, performance_rating &lt;chr&gt;,
## #   total_working_years &lt;dbl&gt;, work_life_balance &lt;chr&gt;, years_at_company &lt;dbl&gt;,
## #   years_since_last_promotion &lt;dbl&gt;</code></pre>
<p>Mit dieser Variante würdest du den neuen Datensatz mit allen weiblichen Mitarbeiterinnen zwar in der Konsole ausgeben. Sobald R-Studio schließt, ist der Datensatz allerdings wieder verloren.</p>
<p>Um den Datensatz dauerhaft zu behalten, hast du zwei Möglichkeiten. Zunächst kannst du den neuen Datensatz als Variable speichern:</p>
<div class="sourceCode" id="cb154"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">hr_women</span> <span class="op">&lt;-</span> <span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">gender</span> <span class="op">==</span> <span class="st">"Female"</span><span class="op">)</span></code></pre></div>
<p>Indem du den Datensatz in einer Variable speicherst, kannst du ihn innerhalb einer R-Session (so lange du R geöffnet hast) aufrufen. Speicherst du den Code in einem Skript, kannst du den Datensatz jedes mal neu berechnen. In der Konsole geht der Code verloren, sobald du R schließt.</p>
<p>Um den Datensatz dauerhaft zu speichern, kannst du ihn als CSV-Datei exportieren (siehe vorheriges Submodul). Hierfür solltest du allerdings wissen, in welchen Order der Datensatz gespeichert wird. Dies kannst du mit getwd() erfahren. Um das Arbeitsverzeichnis zu wechseln, drücke Strg + Umschalt + H auf deiner Tastatur (siehe auch <a href="https://stackoverflow.com/questions/22432344/how-do-you-change-the-default-directory-in-rstudio-or-r">hier</a>).</p>
<div class="sourceCode" id="cb155"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># getwd(), um zu sehen, in welchen Ordner die Daten gespeichert werden </span>
<span class="co"># Strg + Umschalt + H um das Arbeitsverzeinis zu wechseln</span>
<span class="va">human_resources</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">gender</span> <span class="op">==</span> <span class="st">"Female"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://readr.tidyverse.org/reference/write_delim.html">write_csv</a></span><span class="op">(</span><span class="st">"hr_women.csv"</span><span class="op">)</span></code></pre></div>
</div>
<div id="weitere-informationen-zu-den-tidyverse-befehlen" class="section level3" number="3.6.4">
<h3>
<span class="header-section-number">3.6.4</span> Weitere Informationen zu den tidyverse Befehlen<a class="anchor" aria-label="anchor" href="#weitere-informationen-zu-den-tidyverse-befehlen"><i class="fas fa-link"></i></a>
</h3>
<p>Wir haben in diesem Submodul eine Reihe an wichtigen Befehlen kennen gelernt, mit denen wir bereits komplexe Berechnungen in R durchführen können. Nimm dir Zeit, diese Befehle kennen zu lernen, wir werden sie in den Übungen ohnehin mehrmals wiederholen. Solltest du mehr Interesse an tidyverse haben, schau dir folgende Links an:</p>
<ul>
<li><a href="https://www.youtube.com/user/safe4democracy/videos">David Robinson Screencasts</a></li>
<li><a href="https://r4ds.had.co.nz/">R for Data Science</a></li>
<li><a href="https://moderndive.com/3-wrangling.html">ModernDive - Statistical Inference via Data Science - Data Wrangling</a></li>
</ul>
</div>
</div>
<div id="grundlagen-jamovi" class="section level2" number="3.7">
<h2>
<span class="header-section-number">3.7</span> Grundlagen Jamovi<a class="anchor" aria-label="anchor" href="#grundlagen-jamovi"><i class="fas fa-link"></i></a>
</h2>
<p>Jamovi ist eine Statistik-Software, die die Vorteile von einem Grafikprogramm und der Flexibilität einer Programmiersprache verbindet. Einerseits ähnelt die Oberfläche von Jamovi der bekannten, aber kostenpflichtigen Statistik-Software SPSS, andererseits ermöglicht Jamovi die Integration der Ergebnisse in R und ist damit die perfekte Schnittstelle für diesen Kurs. Wir werden in diesem Submodul die Grundlagen von Jamovi kennen lernen, um später mit Jamovi statistische Fragestellungen zu beantworten.</p>
<blockquote>
<p>Für dieses Submodul nehme ich an, dass du Jamovi bereits herunter geladen hast und dir ebenso den Datensatz <a href="data/human_resources.csv">human_resources.csv</a> herunter geladen hast (siehe Datensatz unten dieser Infobox).</p>
</blockquote>
<div id="datensätze-mit-jamovi-einlesen" class="section level3" number="3.7.1">
<h3>
<span class="header-section-number">3.7.1</span> Datensätze mit Jamovi einlesen<a class="anchor" aria-label="anchor" href="#datens%C3%A4tze-mit-jamovi-einlesen"><i class="fas fa-link"></i></a>
</h3>
<p>Öffnest du Jamovi, siehst du lediglich ein leeres Fenster:</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/01.png" width="840"></div>
<p>Wir müssen daher zunächst die Daten in Jamovi einfügen. Hierfür klickst du auf Open -&gt; Import und wählst den Datensatz von deinem PC aus.</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/02.png" width="784"></div>
<p>Im Anschluss solltest du den Datensatz in Jamovi sehen können.</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/03.png" width="840"></div>
</div>
<div id="die-benutzeroberfläche-von-jamovi" class="section level3" number="3.7.2">
<h3>
<span class="header-section-number">3.7.2</span> Die Benutzeroberfläche von Jamovi<a class="anchor" aria-label="anchor" href="#die-benutzeroberfl%C3%A4che-von-jamovi"><i class="fas fa-link"></i></a>
</h3>
<p>Optisch ähnelt Jamovi Excel oder SPSS und ist daher vermutlich intuitiver zu bedienen als R. Wir werden in diesem Semester daher die bekannten statistischen Verfahren mit Jamovi rechnen und R für die Dokumentation deiner Ergebnisse und verschiedener Berechnungen verwenden.</p>
<p>Unter Analyse findest du verschiedene Buttons, mit denen du sowohl statistische Verfahren berechnen kannst, als auch deskriptive Daten des Datensatzes berechnen kannst:</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/04.jpg" width="240"></div>
<p>Diese Bezeichnungen sagen dir vermutlich zu diesem Zeitpunkt nicht viel, das ist auch nicht schlimm, da wir diese Bezeichnungen Stück für Stück in diesem Seminar lernen werden. Im Verlaufe des Semesters werden wir uns ausführlich mit t-Tests, ANOVAs und der Regression beschäftigen.</p>
<p>Unter Data findest du verschiedene Befehle, mit denen du die Daten manipulieren kannst. Wir werden diese Leiste in diesem Seminar kaum benutzen und die Datenmanipulation in R machen.</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/05.jpg" width="388"></div>
</div>
<div id="deskriptive-daten-mit-jamovi-berechnen" class="section level3" number="3.7.3">
<h3>
<span class="header-section-number">3.7.3</span> Deskriptive Daten mit Jamovi berechnen<a class="anchor" aria-label="anchor" href="#deskriptive-daten-mit-jamovi-berechnen"><i class="fas fa-link"></i></a>
</h3>
<p>Nutzen wir Jamovi, um ein paar Einsichten in unseren Datensatz zu gewinnen. Fragen wir uns beispielsweise, wie viel die Mitarbeitende des Unternehmens im Durchschnitt verdienen. Aus dem letzten Semester weißt du, dass man hierzu den Mittelwert einer Variable berechnen muss. In Jamovi klickst du hierfür auf Exploration und anschließend auf Descriptives:</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/06.jpg" width="146"></div>
<p>Nun hast du die Möglichkeit eine Variable auszuwählen und verschiedene Maße der zentralen Tendenz und der Streuung zu berechnen. In unserem Fall möchten wir das mittlere Einkommen aller Mitarbeitenden berechnen:</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/07.png" width="684"></div>
<p>Wie du siehst, habe ich unter Central Tendency Mean ausgewählt und erhalte ein monatliches Bruttoeinkommen von 6503 Euro.</p>
<p>Wir könnten ebenso untersuchen, wie hoch das mittlere Einkommen für Personen mit verschiedenen Bildungsabschlüssen ist. Also, verdienen Mitarbeitende mit einem Masterabschluss mehr als Mitarbeitende mit einem Bachelorabschluss?</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/08.jpg" width="696"></div>
<p>Offensichtlich ja. Im Schnitt verdienen Mitarbeidende mit einem Bachelorabschluss 6517 Euro brutto, mit einem Masterabschluss 6832 Euro brutto. Du erkennst im Bild ebenso, dass ich mir die Standardabweichung der Variablen ausgegeben habe.</p>
<p>Ebenso kannst du dir die Verteilung der Einkommen pro Bildungsabschluss als Visualisierung ausgeben lassen. Hierzu klickst du auf Plots und anschließend auf Histogram:</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/09.jpg" width="794"></div>
</div>
<div id="jamovi-in-r-exportieren" class="section level3" number="3.7.4">
<h3>
<span class="header-section-number">3.7.4</span> Jamovi in R exportieren<a class="anchor" aria-label="anchor" href="#jamovi-in-r-exportieren"><i class="fas fa-link"></i></a>
</h3>
<p>Ein Trick, den wir über den ganzen Kurz verwenden werden, ist es, den Output von Jamovi in R zu übertragen. Wir machen das, um unsere Berechnungen dauerhaft in einem Skript zu speichern und um somit unsere Ergebnisse zu dokumentieren.</p>
<p>Um den den Output in R zu übertragen, musst du zunächst auf die drei Punkte rechts oben in Jamovi klicken:</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/10.jpg" width="840"></div>
<p>Anschließend öffnet sich ein Fenster, in welchem du den Syntax mode aktivierst:</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/11.jpg" width="278"></div>
<p>Wie du sehen kannst, erstellt Jamovi den Output deiner Berechnungen in Form von R-Code. Diesen R-Code kannst du anschließend kopieren.</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/12.png" width="282"></div>
<p>Im nächsten Schritt musst du mehrere Dinge beachten. Zunächst musst du sicher stellen, dass das Paket <a href="https://www.jamovi.org/jmv/">jmv</a> geladen ist (library(jmv)). jmv ist die Schnittstelle zu R. Ist das Paket nicht geladen, wird der Code einen Fehler anzeigen. Ebenso solltest du sicher stellen, dass dein Datensatz importiert ist (siehe Zeile 4 im nächsten Bild). Zuletzt musst du im Jamovi-Code immer den Namen des Datensatzes anpassen (siehe Zeile 8 im nächsten Bild). Ansonsten kann es zu Fehlern kommen.</p>
<div class="inline-figure"><img src="images/02_grundlagen/jamovi/13.png" width="552"></div>
<p>Wie du siehst, erhälst du den gleichen Output wie in Jamovi. Wann solltest du allerdings den Code von Jamovi in R übertragen? Das R-Skript dient der Dokumentation deiner Berechnungen. Alle Berechnungen, die du daher dauerhaft behalten möchtest, sollten in einem R-Skript gespeichert werden. Alle Berechnungen, die du nur einmal ausprobierst, müssen nicht in das R-Skript.</p>
</div>
<div id="zusammenfassung" class="section level3" number="3.7.5">
<h3>
<span class="header-section-number">3.7.5</span> Zusammenfassung<a class="anchor" aria-label="anchor" href="#zusammenfassung"><i class="fas fa-link"></i></a>
</h3>
<p>Die eben beschriebenen Schritte wirst du in diesem Semester immer wieder ausführen, bis du sie auswendig kennst. In diesem Submodul hast du einen kurzen Überblick über die Möglichkeiten von Jamovi erhalten und du hast gesehen, wie Daten in Jamovi importiert werden können. Ebenso hast du gelernt, wie man deskriptive Daten in Jamovi berechnet und in R überführt.</p>

</div>
</div>
</div>
  <div class="chapter-nav">
<div class="empty"></div>
<div class="empty"></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>A Minimal Book Example</strong>" was written by Yihui Xie. It was last built on 2022-01-16.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>
</body>
</html>
